//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 03/12/2015 18:03:06
namespace NewImpossibleGame
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        public sealed class Assets
        {
            
            public sealed class Levels
            {
                
                /// <summary> Path to Content/Assets/Levels/level1A.level </summary>
                public const string level1A_level = "Content/Assets/Levels/level1A.level";
            }
            
            public sealed class Materials
            {
                
                /// <summary> Path to Content/Assets/Materials/golfNormal.jpg </summary>
                public const string golfNormal_jpg = "Content/Assets/Materials/golfNormal.jpg";
                
                /// <summary> Path to Content/Assets/Materials/BoxMaterial.wmat </summary>
                public const string BoxMaterial = "Content/Assets/Materials/BoxMaterial.wmat";
                
                /// <summary> Path to Content/Assets/Materials/DownTubeMaterial.wmat </summary>
                public const string DownTubeMaterial = "Content/Assets/Materials/DownTubeMaterial.wmat";
                
                /// <summary> Path to Content/Assets/Materials/GroundMaterial.wmat </summary>
                public const string GroundMaterial = "Content/Assets/Materials/GroundMaterial.wmat";
                
                /// <summary> Path to Content/Assets/Materials/NailMaterial.wmat </summary>
                public const string NailMaterial = "Content/Assets/Materials/NailMaterial.wmat";
                
                /// <summary> Path to Content/Assets/Materials/PlayerMaterial.wmat </summary>
                public const string PlayerMaterial = "Content/Assets/Materials/PlayerMaterial.wmat";
                
                /// <summary> Path to Content/Assets/Materials/SpeederMaterial.wmat </summary>
                public const string SpeederMaterial = "Content/Assets/Materials/SpeederMaterial.wmat";
                
                /// <summary> Path to Content/Assets/Materials/SpikeMaterial.wmat </summary>
                public const string SpikeMaterial = "Content/Assets/Materials/SpikeMaterial.wmat";
                
                /// <summary> Path to Content/Assets/Materials/TopTubeMaterial.wmat </summary>
                public const string TopTubeMaterial = "Content/Assets/Materials/TopTubeMaterial.wmat";
                
                /// <summary> Path to Content/Assets/Materials/VolumeMaterial.wmat </summary>
                public const string VolumeMaterial = "Content/Assets/Materials/VolumeMaterial.wmat";
            }
            
            public sealed class Textures
            {
                
                /// <summary> Path to Content/Assets/Textures/boxTexture.jpg </summary>
                public const string boxTexture_jpg = "Content/Assets/Textures/boxTexture.jpg";
                
                /// <summary> Path to Content/Assets/Textures/floor.png </summary>
                public const string floor_png = "Content/Assets/Textures/floor.png";
                
                /// <summary> Path to Content/Assets/Textures/nailBlock.png </summary>
                public const string nailBlock_png = "Content/Assets/Textures/nailBlock.png";
                
                /// <summary> Path to Content/Assets/Textures/Speeder.jpg </summary>
                public const string Speeder_jpg = "Content/Assets/Textures/Speeder.jpg";
                
                /// <summary> Path to Content/Assets/Textures/SpikeTexture.jpg </summary>
                public const string SpikeTexture_jpg = "Content/Assets/Textures/SpikeTexture.jpg";
                
                /// <summary> Path to Content/Assets/Textures/TopTube.png </summary>
                public const string TopTube_png = "Content/Assets/Textures/TopTube.png";
                
                /// <summary> Path to Content/Assets/Textures/volumeBlock.png </summary>
                public const string volumeBlock_png = "Content/Assets/Textures/volumeBlock.png";
            }
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/Stage1.wscene </summary>
            public const string Stage1 = "Content/Scenes/Stage1.wscene";
        }
    }
}
