//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 17/11/2015 17:17:35
namespace NewImpossibleGame
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        public sealed class Assets
        {
            
            public sealed class Levels
            {
                
                /// <summary> Path to Content/Assets/Levels/level1A.level </summary>
                public const string level1A_level = "Content/Assets/Levels/level1A.level";
            }
            
            public sealed class Materials
            {
                
                /// <summary> Path to Content/Assets/Materials/golfNormal.jpg </summary>
                public const string golfNormal_jpg = "Content/Assets/Materials/golfNormal.jpg";
                
                /// <summary> Path to Content/Assets/Materials/PlayerMaterial.wmat </summary>
                public const string PlayerMaterial = "Content/Assets/Materials/PlayerMaterial.wmat";
            }
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
