//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 09/05/2017 18:48:03
namespace SuperSlingshot
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        public sealed class Assets
        {
            
            /// <summary> Path to Content/Assets/elastic_line.png </summary>
            public const string elastic_line_png = "Content/Assets/elastic_line.png";
            
            /// <summary> Path to Content/Assets/standard_line.png </summary>
            public const string standard_line_png = "Content/Assets/standard_line.png";
            
            public sealed class Breakables
            {
                
                /// <summary> Path to Content/Assets/Breakables/glass1x1c.png </summary>
                public const string glass1x1c_png = "Content/Assets/Breakables/glass1x1c.png";
                
                /// <summary> Path to Content/Assets/Breakables/glass1x1cb.png </summary>
                public const string glass1x1cb_png = "Content/Assets/Breakables/glass1x1cb.png";
                
                /// <summary> Path to Content/Assets/Breakables/glass1x1r.png </summary>
                public const string glass1x1r_png = "Content/Assets/Breakables/glass1x1r.png";
                
                /// <summary> Path to Content/Assets/Breakables/glass1x1rb.png </summary>
                public const string glass1x1rb_png = "Content/Assets/Breakables/glass1x1rb.png";
                
                /// <summary> Path to Content/Assets/Breakables/glass1x1t.png </summary>
                public const string glass1x1t_png = "Content/Assets/Breakables/glass1x1t.png";
                
                /// <summary> Path to Content/Assets/Breakables/glass1x1tb.png </summary>
                public const string glass1x1tb_png = "Content/Assets/Breakables/glass1x1tb.png";
                
                /// <summary> Path to Content/Assets/Breakables/glass1x2r.png </summary>
                public const string glass1x2r_png = "Content/Assets/Breakables/glass1x2r.png";
                
                /// <summary> Path to Content/Assets/Breakables/glass1x2rb.png </summary>
                public const string glass1x2rb_png = "Content/Assets/Breakables/glass1x2rb.png";
                
                /// <summary> Path to Content/Assets/Breakables/glass1x3r.png </summary>
                public const string glass1x3r_png = "Content/Assets/Breakables/glass1x3r.png";
                
                /// <summary> Path to Content/Assets/Breakables/glass1x3rb.png </summary>
                public const string glass1x3rb_png = "Content/Assets/Breakables/glass1x3rb.png";
                
                /// <summary> Path to Content/Assets/Breakables/glass2x1r.png </summary>
                public const string glass2x1r_png = "Content/Assets/Breakables/glass2x1r.png";
                
                /// <summary> Path to Content/Assets/Breakables/glass2x1rb.png </summary>
                public const string glass2x1rb_png = "Content/Assets/Breakables/glass2x1rb.png";
                
                /// <summary> Path to Content/Assets/Breakables/glass2x1t.png </summary>
                public const string glass2x1t_png = "Content/Assets/Breakables/glass2x1t.png";
                
                /// <summary> Path to Content/Assets/Breakables/glass2x1tb.png </summary>
                public const string glass2x1tb_png = "Content/Assets/Breakables/glass2x1tb.png";
                
                /// <summary> Path to Content/Assets/Breakables/glass2x2r.png </summary>
                public const string glass2x2r_png = "Content/Assets/Breakables/glass2x2r.png";
                
                /// <summary> Path to Content/Assets/Breakables/glass2x2rb.png </summary>
                public const string glass2x2rb_png = "Content/Assets/Breakables/glass2x2rb.png";
                
                /// <summary> Path to Content/Assets/Breakables/glass2x3r.png </summary>
                public const string glass2x3r_png = "Content/Assets/Breakables/glass2x3r.png";
                
                /// <summary> Path to Content/Assets/Breakables/glass2x3rb.png </summary>
                public const string glass2x3rb_png = "Content/Assets/Breakables/glass2x3rb.png";
                
                /// <summary> Path to Content/Assets/Breakables/glass3x1r.png </summary>
                public const string glass3x1r_png = "Content/Assets/Breakables/glass3x1r.png";
                
                /// <summary> Path to Content/Assets/Breakables/glass3x1rb.png </summary>
                public const string glass3x1rb_png = "Content/Assets/Breakables/glass3x1rb.png";
                
                /// <summary> Path to Content/Assets/Breakables/glass3x2r.png </summary>
                public const string glass3x2r_png = "Content/Assets/Breakables/glass3x2r.png";
                
                /// <summary> Path to Content/Assets/Breakables/glass3x2rb.png </summary>
                public const string glass3x2rb_png = "Content/Assets/Breakables/glass3x2rb.png";
                
                /// <summary> Path to Content/Assets/Breakables/metal1x1c.png </summary>
                public const string metal1x1c_png = "Content/Assets/Breakables/metal1x1c.png";
                
                /// <summary> Path to Content/Assets/Breakables/metal1x1cb.png </summary>
                public const string metal1x1cb_png = "Content/Assets/Breakables/metal1x1cb.png";
                
                /// <summary> Path to Content/Assets/Breakables/metal1x1r.png </summary>
                public const string metal1x1r_png = "Content/Assets/Breakables/metal1x1r.png";
                
                /// <summary> Path to Content/Assets/Breakables/metal1x1rb.png </summary>
                public const string metal1x1rb_png = "Content/Assets/Breakables/metal1x1rb.png";
                
                /// <summary> Path to Content/Assets/Breakables/metal1x1t.png </summary>
                public const string metal1x1t_png = "Content/Assets/Breakables/metal1x1t.png";
                
                /// <summary> Path to Content/Assets/Breakables/metal1x1tb.png </summary>
                public const string metal1x1tb_png = "Content/Assets/Breakables/metal1x1tb.png";
                
                /// <summary> Path to Content/Assets/Breakables/metal1x2r.png </summary>
                public const string metal1x2r_png = "Content/Assets/Breakables/metal1x2r.png";
                
                /// <summary> Path to Content/Assets/Breakables/metal1x2rb.png </summary>
                public const string metal1x2rb_png = "Content/Assets/Breakables/metal1x2rb.png";
                
                /// <summary> Path to Content/Assets/Breakables/metal1x3r.png </summary>
                public const string metal1x3r_png = "Content/Assets/Breakables/metal1x3r.png";
                
                /// <summary> Path to Content/Assets/Breakables/metal1x3rb.png </summary>
                public const string metal1x3rb_png = "Content/Assets/Breakables/metal1x3rb.png";
                
                /// <summary> Path to Content/Assets/Breakables/metal2x1r.png </summary>
                public const string metal2x1r_png = "Content/Assets/Breakables/metal2x1r.png";
                
                /// <summary> Path to Content/Assets/Breakables/metal2x1rb.png </summary>
                public const string metal2x1rb_png = "Content/Assets/Breakables/metal2x1rb.png";
                
                /// <summary> Path to Content/Assets/Breakables/metal2x1t.png </summary>
                public const string metal2x1t_png = "Content/Assets/Breakables/metal2x1t.png";
                
                /// <summary> Path to Content/Assets/Breakables/metal2x1tb.png </summary>
                public const string metal2x1tb_png = "Content/Assets/Breakables/metal2x1tb.png";
                
                /// <summary> Path to Content/Assets/Breakables/metal2x2r.png </summary>
                public const string metal2x2r_png = "Content/Assets/Breakables/metal2x2r.png";
                
                /// <summary> Path to Content/Assets/Breakables/metal2x2rb.png </summary>
                public const string metal2x2rb_png = "Content/Assets/Breakables/metal2x2rb.png";
                
                /// <summary> Path to Content/Assets/Breakables/metal2x3r.png </summary>
                public const string metal2x3r_png = "Content/Assets/Breakables/metal2x3r.png";
                
                /// <summary> Path to Content/Assets/Breakables/metal2x3rb.png </summary>
                public const string metal2x3rb_png = "Content/Assets/Breakables/metal2x3rb.png";
                
                /// <summary> Path to Content/Assets/Breakables/metal3x1r.png </summary>
                public const string metal3x1r_png = "Content/Assets/Breakables/metal3x1r.png";
                
                /// <summary> Path to Content/Assets/Breakables/metal3x1rb.png </summary>
                public const string metal3x1rb_png = "Content/Assets/Breakables/metal3x1rb.png";
                
                /// <summary> Path to Content/Assets/Breakables/metal3x2r.png </summary>
                public const string metal3x2r_png = "Content/Assets/Breakables/metal3x2r.png";
                
                /// <summary> Path to Content/Assets/Breakables/metal3x2rb.png </summary>
                public const string metal3x2rb_png = "Content/Assets/Breakables/metal3x2rb.png";
                
                /// <summary> Path to Content/Assets/Breakables/stone1x1c.png </summary>
                public const string stone1x1c_png = "Content/Assets/Breakables/stone1x1c.png";
                
                /// <summary> Path to Content/Assets/Breakables/stone1x1cb.png </summary>
                public const string stone1x1cb_png = "Content/Assets/Breakables/stone1x1cb.png";
                
                /// <summary> Path to Content/Assets/Breakables/stone1x1r.png </summary>
                public const string stone1x1r_png = "Content/Assets/Breakables/stone1x1r.png";
                
                /// <summary> Path to Content/Assets/Breakables/stone1x1rb.png </summary>
                public const string stone1x1rb_png = "Content/Assets/Breakables/stone1x1rb.png";
                
                /// <summary> Path to Content/Assets/Breakables/stone1x1t.png </summary>
                public const string stone1x1t_png = "Content/Assets/Breakables/stone1x1t.png";
                
                /// <summary> Path to Content/Assets/Breakables/stone1x1tb.png </summary>
                public const string stone1x1tb_png = "Content/Assets/Breakables/stone1x1tb.png";
                
                /// <summary> Path to Content/Assets/Breakables/stone1x2.png </summary>
                public const string stone1x2_png = "Content/Assets/Breakables/stone1x2.png";
                
                /// <summary> Path to Content/Assets/Breakables/stone1x2rb.png </summary>
                public const string stone1x2rb_png = "Content/Assets/Breakables/stone1x2rb.png";
                
                /// <summary> Path to Content/Assets/Breakables/stone1x3r.png </summary>
                public const string stone1x3r_png = "Content/Assets/Breakables/stone1x3r.png";
                
                /// <summary> Path to Content/Assets/Breakables/stone1x3rb.png </summary>
                public const string stone1x3rb_png = "Content/Assets/Breakables/stone1x3rb.png";
                
                /// <summary> Path to Content/Assets/Breakables/stone2x1r.png </summary>
                public const string stone2x1r_png = "Content/Assets/Breakables/stone2x1r.png";
                
                /// <summary> Path to Content/Assets/Breakables/stone2x1rb.png </summary>
                public const string stone2x1rb_png = "Content/Assets/Breakables/stone2x1rb.png";
                
                /// <summary> Path to Content/Assets/Breakables/stone2x1t.png </summary>
                public const string stone2x1t_png = "Content/Assets/Breakables/stone2x1t.png";
                
                /// <summary> Path to Content/Assets/Breakables/stone2x1tb.png </summary>
                public const string stone2x1tb_png = "Content/Assets/Breakables/stone2x1tb.png";
                
                /// <summary> Path to Content/Assets/Breakables/stone2x2r.png </summary>
                public const string stone2x2r_png = "Content/Assets/Breakables/stone2x2r.png";
                
                /// <summary> Path to Content/Assets/Breakables/stone2x2rb.png </summary>
                public const string stone2x2rb_png = "Content/Assets/Breakables/stone2x2rb.png";
                
                /// <summary> Path to Content/Assets/Breakables/stone2x3r.png </summary>
                public const string stone2x3r_png = "Content/Assets/Breakables/stone2x3r.png";
                
                /// <summary> Path to Content/Assets/Breakables/stone2x3rb.png </summary>
                public const string stone2x3rb_png = "Content/Assets/Breakables/stone2x3rb.png";
                
                /// <summary> Path to Content/Assets/Breakables/stone3x1r.png </summary>
                public const string stone3x1r_png = "Content/Assets/Breakables/stone3x1r.png";
                
                /// <summary> Path to Content/Assets/Breakables/stone3x1rb.png </summary>
                public const string stone3x1rb_png = "Content/Assets/Breakables/stone3x1rb.png";
                
                /// <summary> Path to Content/Assets/Breakables/stone3x2r.png </summary>
                public const string stone3x2r_png = "Content/Assets/Breakables/stone3x2r.png";
                
                /// <summary> Path to Content/Assets/Breakables/stone3x2rb.png </summary>
                public const string stone3x2rb_png = "Content/Assets/Breakables/stone3x2rb.png";
                
                /// <summary> Path to Content/Assets/Breakables/wood1x1c.png </summary>
                public const string wood1x1c_png = "Content/Assets/Breakables/wood1x1c.png";
                
                /// <summary> Path to Content/Assets/Breakables/wood1x1cb.png </summary>
                public const string wood1x1cb_png = "Content/Assets/Breakables/wood1x1cb.png";
                
                /// <summary> Path to Content/Assets/Breakables/wood1x1r.png </summary>
                public const string wood1x1r_png = "Content/Assets/Breakables/wood1x1r.png";
                
                /// <summary> Path to Content/Assets/Breakables/wood1x1rb.png </summary>
                public const string wood1x1rb_png = "Content/Assets/Breakables/wood1x1rb.png";
                
                /// <summary> Path to Content/Assets/Breakables/wood1x1t.png </summary>
                public const string wood1x1t_png = "Content/Assets/Breakables/wood1x1t.png";
                
                /// <summary> Path to Content/Assets/Breakables/wood1x1tb.png </summary>
                public const string wood1x1tb_png = "Content/Assets/Breakables/wood1x1tb.png";
                
                /// <summary> Path to Content/Assets/Breakables/wood1x2r.png </summary>
                public const string wood1x2r_png = "Content/Assets/Breakables/wood1x2r.png";
                
                /// <summary> Path to Content/Assets/Breakables/wood1x2tb.png </summary>
                public const string wood1x2tb_png = "Content/Assets/Breakables/wood1x2tb.png";
                
                /// <summary> Path to Content/Assets/Breakables/wood1x3r.png </summary>
                public const string wood1x3r_png = "Content/Assets/Breakables/wood1x3r.png";
                
                /// <summary> Path to Content/Assets/Breakables/wood1x3rb.png </summary>
                public const string wood1x3rb_png = "Content/Assets/Breakables/wood1x3rb.png";
                
                /// <summary> Path to Content/Assets/Breakables/wood2x1r.png </summary>
                public const string wood2x1r_png = "Content/Assets/Breakables/wood2x1r.png";
                
                /// <summary> Path to Content/Assets/Breakables/wood2x1rb.png </summary>
                public const string wood2x1rb_png = "Content/Assets/Breakables/wood2x1rb.png";
                
                /// <summary> Path to Content/Assets/Breakables/wood2x1t.png </summary>
                public const string wood2x1t_png = "Content/Assets/Breakables/wood2x1t.png";
                
                /// <summary> Path to Content/Assets/Breakables/wood2x1tb.png </summary>
                public const string wood2x1tb_png = "Content/Assets/Breakables/wood2x1tb.png";
                
                /// <summary> Path to Content/Assets/Breakables/wood2x2r.png </summary>
                public const string wood2x2r_png = "Content/Assets/Breakables/wood2x2r.png";
                
                /// <summary> Path to Content/Assets/Breakables/wood2x2rb.png </summary>
                public const string wood2x2rb_png = "Content/Assets/Breakables/wood2x2rb.png";
                
                /// <summary> Path to Content/Assets/Breakables/wood2x3r.png </summary>
                public const string wood2x3r_png = "Content/Assets/Breakables/wood2x3r.png";
                
                /// <summary> Path to Content/Assets/Breakables/wood2x3rb.png </summary>
                public const string wood2x3rb_png = "Content/Assets/Breakables/wood2x3rb.png";
                
                /// <summary> Path to Content/Assets/Breakables/wood3x1r.png </summary>
                public const string wood3x1r_png = "Content/Assets/Breakables/wood3x1r.png";
                
                /// <summary> Path to Content/Assets/Breakables/wood3x1rb.png </summary>
                public const string wood3x1rb_png = "Content/Assets/Breakables/wood3x1rb.png";
                
                /// <summary> Path to Content/Assets/Breakables/wood3x2r.png </summary>
                public const string wood3x2r_png = "Content/Assets/Breakables/wood3x2r.png";
                
                /// <summary> Path to Content/Assets/Breakables/wood3x2rb.png </summary>
                public const string wood3x2rb_png = "Content/Assets/Breakables/wood3x2rb.png";
            }
            
            public sealed class Fonts
            {
                
                /// <summary> Path to Content/Assets/Fonts/Komika Axis_36.ttf </summary>
                public const string Komika_Axis_36_ttf = "Content/Assets/Fonts/Komika Axis_36.ttf";
                
                /// <summary> Path to Content/Assets/Fonts/sketches_16.ttf </summary>
                public const string sketches_16_ttf = "Content/Assets/Fonts/sketches_16.ttf";
                
                /// <summary> Path to Content/Assets/Fonts/sketches_36.ttf </summary>
                public const string sketches_36_ttf = "Content/Assets/Fonts/sketches_36.ttf";
                
                /// <summary> Path to Content/Assets/Fonts/sketches_48.ttf </summary>
                public const string sketches_48_ttf = "Content/Assets/Fonts/sketches_48.ttf";
            }
            
            public sealed class Gui
            {
                
                /// <summary> Path to Content/Assets/Gui/buttons_placeholder.png </summary>
                public const string buttons_placeholder_png = "Content/Assets/Gui/buttons_placeholder.png";
                
                /// <summary> Path to Content/Assets/Gui/button_blocked.png </summary>
                public const string button_blocked_png = "Content/Assets/Gui/button_blocked.png";
                
                /// <summary> Path to Content/Assets/Gui/button_click.png </summary>
                public const string button_click_png = "Content/Assets/Gui/button_click.png";
                
                /// <summary> Path to Content/Assets/Gui/button_hover.png </summary>
                public const string button_hover_png = "Content/Assets/Gui/button_hover.png";
                
                /// <summary> Path to Content/Assets/Gui/button_normal.png </summary>
                public const string button_normal_png = "Content/Assets/Gui/button_normal.png";
                
                /// <summary> Path to Content/Assets/Gui/coin.png </summary>
                public const string coin_png = "Content/Assets/Gui/coin.png";
                
                /// <summary> Path to Content/Assets/Gui/congrats.png </summary>
                public const string congrats_png = "Content/Assets/Gui/congrats.png";
                
                /// <summary> Path to Content/Assets/Gui/crown.png </summary>
                public const string crown_png = "Content/Assets/Gui/crown.png";
                
                /// <summary> Path to Content/Assets/Gui/gem.png </summary>
                public const string gem_png = "Content/Assets/Gui/gem.png";
                
                /// <summary> Path to Content/Assets/Gui/home_small_button_blocked.png </summary>
                public const string home_small_button_blocked_png = "Content/Assets/Gui/home_small_button_blocked.png";
                
                /// <summary> Path to Content/Assets/Gui/home_small_button_click.png </summary>
                public const string home_small_button_click_png = "Content/Assets/Gui/home_small_button_click.png";
                
                /// <summary> Path to Content/Assets/Gui/home_small_button_hover.png </summary>
                public const string home_small_button_hover_png = "Content/Assets/Gui/home_small_button_hover.png";
                
                /// <summary> Path to Content/Assets/Gui/home_small_button_normal.png </summary>
                public const string home_small_button_normal_png = "Content/Assets/Gui/home_small_button_normal.png";
                
                /// <summary> Path to Content/Assets/Gui/menu_background.9.png </summary>
                public const string menu_background_9_png = "Content/Assets/Gui/menu_background.9.png";
                
                /// <summary> Path to Content/Assets/Gui/menu_header.9.png </summary>
                public const string menu_header_9_png = "Content/Assets/Gui/menu_header.9.png";
                
                /// <summary> Path to Content/Assets/Gui/menu_small_button_blocked.png </summary>
                public const string menu_small_button_blocked_png = "Content/Assets/Gui/menu_small_button_blocked.png";
                
                /// <summary> Path to Content/Assets/Gui/menu_small_button_click.png </summary>
                public const string menu_small_button_click_png = "Content/Assets/Gui/menu_small_button_click.png";
                
                /// <summary> Path to Content/Assets/Gui/menu_small_button_hover.png </summary>
                public const string menu_small_button_hover_png = "Content/Assets/Gui/menu_small_button_hover.png";
                
                /// <summary> Path to Content/Assets/Gui/menu_small_button_normal.png </summary>
                public const string menu_small_button_normal_png = "Content/Assets/Gui/menu_small_button_normal.png";
                
                /// <summary> Path to Content/Assets/Gui/next_small_button_blocked.png </summary>
                public const string next_small_button_blocked_png = "Content/Assets/Gui/next_small_button_blocked.png";
                
                /// <summary> Path to Content/Assets/Gui/next_small_button_click.png </summary>
                public const string next_small_button_click_png = "Content/Assets/Gui/next_small_button_click.png";
                
                /// <summary> Path to Content/Assets/Gui/next_small_button_hover.png </summary>
                public const string next_small_button_hover_png = "Content/Assets/Gui/next_small_button_hover.png";
                
                /// <summary> Path to Content/Assets/Gui/next_small_button_normal.png </summary>
                public const string next_small_button_normal_png = "Content/Assets/Gui/next_small_button_normal.png";
                
                /// <summary> Path to Content/Assets/Gui/pause_small_button_blocked.png </summary>
                public const string pause_small_button_blocked_png = "Content/Assets/Gui/pause_small_button_blocked.png";
                
                /// <summary> Path to Content/Assets/Gui/pause_small_button_click.png </summary>
                public const string pause_small_button_click_png = "Content/Assets/Gui/pause_small_button_click.png";
                
                /// <summary> Path to Content/Assets/Gui/pause_small_button_hover.png </summary>
                public const string pause_small_button_hover_png = "Content/Assets/Gui/pause_small_button_hover.png";
                
                /// <summary> Path to Content/Assets/Gui/pause_small_button_normal.png </summary>
                public const string pause_small_button_normal_png = "Content/Assets/Gui/pause_small_button_normal.png";
                
                /// <summary> Path to Content/Assets/Gui/play_small_button_blocked.png </summary>
                public const string play_small_button_blocked_png = "Content/Assets/Gui/play_small_button_blocked.png";
                
                /// <summary> Path to Content/Assets/Gui/play_small_button_click.png </summary>
                public const string play_small_button_click_png = "Content/Assets/Gui/play_small_button_click.png";
                
                /// <summary> Path to Content/Assets/Gui/play_small_button_hover.png </summary>
                public const string play_small_button_hover_png = "Content/Assets/Gui/play_small_button_hover.png";
                
                /// <summary> Path to Content/Assets/Gui/play_small_button_normal.png </summary>
                public const string play_small_button_normal_png = "Content/Assets/Gui/play_small_button_normal.png";
                
                /// <summary> Path to Content/Assets/Gui/replay_small_button_blocked.png </summary>
                public const string replay_small_button_blocked_png = "Content/Assets/Gui/replay_small_button_blocked.png";
                
                /// <summary> Path to Content/Assets/Gui/replay_small_button_click.png </summary>
                public const string replay_small_button_click_png = "Content/Assets/Gui/replay_small_button_click.png";
                
                /// <summary> Path to Content/Assets/Gui/replay_small_button_hover.png </summary>
                public const string replay_small_button_hover_png = "Content/Assets/Gui/replay_small_button_hover.png";
                
                /// <summary> Path to Content/Assets/Gui/replay_small_button_normal.png </summary>
                public const string replay_small_button_normal_png = "Content/Assets/Gui/replay_small_button_normal.png";
                
                /// <summary> Path to Content/Assets/Gui/score_paceholder.png </summary>
                public const string score_paceholder_png = "Content/Assets/Gui/score_paceholder.png";
                
                /// <summary> Path to Content/Assets/Gui/small_button_blocked.png </summary>
                public const string small_button_blocked_png = "Content/Assets/Gui/small_button_blocked.png";
                
                /// <summary> Path to Content/Assets/Gui/small_button_click.png </summary>
                public const string small_button_click_png = "Content/Assets/Gui/small_button_click.png";
                
                /// <summary> Path to Content/Assets/Gui/small_button_hover.png </summary>
                public const string small_button_hover_png = "Content/Assets/Gui/small_button_hover.png";
                
                /// <summary> Path to Content/Assets/Gui/small_button_normal.png </summary>
                public const string small_button_normal_png = "Content/Assets/Gui/small_button_normal.png";
                
                /// <summary> Path to Content/Assets/Gui/star.png </summary>
                public const string star_png = "Content/Assets/Gui/star.png";
                
                /// <summary> Path to Content/Assets/Gui/star_placeholder.png </summary>
                public const string star_placeholder_png = "Content/Assets/Gui/star_placeholder.png";
            }
            
            public sealed class Other
            {
                
                /// <summary> Path to Content/Assets/Other/cloud1.png </summary>
                public const string cloud1_png = "Content/Assets/Other/cloud1.png";
                
                /// <summary> Path to Content/Assets/Other/cloud2.png </summary>
                public const string cloud2_png = "Content/Assets/Other/cloud2.png";
                
                /// <summary> Path to Content/Assets/Other/cloud3.png </summary>
                public const string cloud3_png = "Content/Assets/Other/cloud3.png";
                
                /// <summary> Path to Content/Assets/Other/cloud4.png </summary>
                public const string cloud4_png = "Content/Assets/Other/cloud4.png";
                
                /// <summary> Path to Content/Assets/Other/cloud5.png </summary>
                public const string cloud5_png = "Content/Assets/Other/cloud5.png";
                
                /// <summary> Path to Content/Assets/Other/cloud6.png </summary>
                public const string cloud6_png = "Content/Assets/Other/cloud6.png";
                
                /// <summary> Path to Content/Assets/Other/cloud7.png </summary>
                public const string cloud7_png = "Content/Assets/Other/cloud7.png";
                
                /// <summary> Path to Content/Assets/Other/crate.png </summary>
                public const string crate_png = "Content/Assets/Other/crate.png";
                
                /// <summary> Path to Content/Assets/Other/particle1.png </summary>
                public const string particle1_png = "Content/Assets/Other/particle1.png";
                
                /// <summary> Path to Content/Assets/Other/snowparticle.png </summary>
                public const string snowparticle_png = "Content/Assets/Other/snowparticle.png";
            }
            
            public sealed class Sounds
            {
                
                /// <summary> Path to Content/Assets/Sounds/backgroundmusic.mp3 </summary>
                public const string backgroundmusic_mp3 = "Content/Assets/Sounds/backgroundmusic.mp3";
                
                /// <summary> Path to Content/Assets/Sounds/Crash.wav </summary>
                public const string Crash_wav = "Content/Assets/Sounds/Crash.wav";
                
                /// <summary> Path to Content/Assets/Sounds/Launch.wav </summary>
                public const string Launch_wav = "Content/Assets/Sounds/Launch.wav";
                
                /// <summary> Path to Content/Assets/Sounds/Rubber.wav </summary>
                public const string Rubber_wav = "Content/Assets/Sounds/Rubber.wav";
            }
            
            public sealed class Stones
            {
                
                /// <summary> Path to Content/Assets/Stones/Barney.png </summary>
                public const string Barney_png = "Content/Assets/Stones/Barney.png";
                
                /// <summary> Path to Content/Assets/Stones/Farley.png </summary>
                public const string Farley_png = "Content/Assets/Stones/Farley.png";
                
                /// <summary> Path to Content/Assets/Stones/InTheAir.png </summary>
                public const string InTheAir_png = "Content/Assets/Stones/InTheAir.png";
                
                /// <summary> Path to Content/Assets/Stones/Prepared.png </summary>
                public const string Prepared_png = "Content/Assets/Stones/Prepared.png";
                
                /// <summary> Path to Content/Assets/Stones/Puddin.png </summary>
                public const string Puddin_png = "Content/Assets/Stones/Puddin.png";
                
                /// <summary> Path to Content/Assets/Stones/Stamped.png </summary>
                public const string Stamped_png = "Content/Assets/Stones/Stamped.png";
            }
            
            public sealed class Tiles
            {
                
                /// <summary> Path to Content/Assets/Tiles/desert adorners.png </summary>
                public const string desert_adorners_png = "Content/Assets/Tiles/desert adorners.png";
                
                /// <summary> Path to Content/Assets/Tiles/desert background.png </summary>
                public const string desert_background_png = "Content/Assets/Tiles/desert background.png";
                
                /// <summary> Path to Content/Assets/Tiles/desert small.png </summary>
                public const string desert_small_png = "Content/Assets/Tiles/desert small.png";
                
                /// <summary> Path to Content/Assets/Tiles/desert.png </summary>
                public const string desert_png = "Content/Assets/Tiles/desert.png";
                
                /// <summary> Path to Content/Assets/Tiles/grass.png </summary>
                public const string grass_png = "Content/Assets/Tiles/grass.png";
                
                /// <summary> Path to Content/Assets/Tiles/halloween background.png </summary>
                public const string halloween_background_png = "Content/Assets/Tiles/halloween background.png";
                
                /// <summary> Path to Content/Assets/Tiles/halloween.png </summary>
                public const string halloween_png = "Content/Assets/Tiles/halloween.png";
                
                /// <summary> Path to Content/Assets/Tiles/initial background.png </summary>
                public const string initial_background_png = "Content/Assets/Tiles/initial background.png";
                
                /// <summary> Path to Content/Assets/Tiles/Initial.tmx </summary>
                public const string Initial_tmx = "Content/Assets/Tiles/Initial.tmx";
                
                /// <summary> Path to Content/Assets/Tiles/initialAssets.png </summary>
                public const string initialAssets_png = "Content/Assets/Tiles/initialAssets.png";
                
                /// <summary> Path to Content/Assets/Tiles/Level1.tmx </summary>
                public const string Level1_tmx = "Content/Assets/Tiles/Level1.tmx";
                
                /// <summary> Path to Content/Assets/Tiles/Level2.tmx </summary>
                public const string Level2_tmx = "Content/Assets/Tiles/Level2.tmx";
                
                /// <summary> Path to Content/Assets/Tiles/Level3.tmx </summary>
                public const string Level3_tmx = "Content/Assets/Tiles/Level3.tmx";
                
                /// <summary> Path to Content/Assets/Tiles/Level4.tmx </summary>
                public const string Level4_tmx = "Content/Assets/Tiles/Level4.tmx";
                
                /// <summary> Path to Content/Assets/Tiles/SlingShot2A.png </summary>
                public const string SlingShot2A_png = "Content/Assets/Tiles/SlingShot2A.png";
                
                /// <summary> Path to Content/Assets/Tiles/SlingShot2B.png </summary>
                public const string SlingShot2B_png = "Content/Assets/Tiles/SlingShot2B.png";
                
                /// <summary> Path to Content/Assets/Tiles/SlingShotA.png </summary>
                public const string SlingShotA_png = "Content/Assets/Tiles/SlingShotA.png";
                
                /// <summary> Path to Content/Assets/Tiles/SlingShotB.png </summary>
                public const string SlingShotB_png = "Content/Assets/Tiles/SlingShotB.png";
                
                /// <summary> Path to Content/Assets/Tiles/snow back adorners.png </summary>
                public const string snow_back_adorners_png = "Content/Assets/Tiles/snow back adorners.png";
                
                /// <summary> Path to Content/Assets/Tiles/snow background.png </summary>
                public const string snow_background_png = "Content/Assets/Tiles/snow background.png";
                
                /// <summary> Path to Content/Assets/Tiles/snow front adorners.png </summary>
                public const string snow_front_adorners_png = "Content/Assets/Tiles/snow front adorners.png";
                
                /// <summary> Path to Content/Assets/Tiles/snow.png </summary>
                public const string snow_png = "Content/Assets/Tiles/snow.png";
            }
        }
        
        public sealed class Prefabs
        {
            
            /// <summary> Path to Content/Prefabs/menuButton.wpref </summary>
            public const string menuButton = "Content/Prefabs/menuButton.wpref";
            
            /// <summary> Path to Content/Prefabs/menuScoreButton.wpref </summary>
            public const string menuScoreButton = "Content/Prefabs/menuScoreButton.wpref";
            
            /// <summary> Path to Content/Prefabs/menuSmallButton.wpref </summary>
            public const string menuSmallButton = "Content/Prefabs/menuSmallButton.wpref";
            
            /// <summary> Path to Content/Prefabs/star.wpref </summary>
            public const string star = "Content/Prefabs/star.wpref";
            
            /// <summary> Path to Content/Prefabs/wc1x1.wpref </summary>
            public const string wc1x1 = "Content/Prefabs/wc1x1.wpref";
            
            /// <summary> Path to Content/Prefabs/wr1x1.wpref </summary>
            public const string wr1x1 = "Content/Prefabs/wr1x1.wpref";
            
            /// <summary> Path to Content/Prefabs/wr1x2.wpref </summary>
            public const string wr1x2 = "Content/Prefabs/wr1x2.wpref";
            
            /// <summary> Path to Content/Prefabs/wr1x3.wpref </summary>
            public const string wr1x3 = "Content/Prefabs/wr1x3.wpref";
            
            /// <summary> Path to Content/Prefabs/wr2x1.wpref </summary>
            public const string wr2x1 = "Content/Prefabs/wr2x1.wpref";
            
            /// <summary> Path to Content/Prefabs/wr2x2.wpref </summary>
            public const string wr2x2 = "Content/Prefabs/wr2x2.wpref";
            
            /// <summary> Path to Content/Prefabs/wr2x3.wpref </summary>
            public const string wr2x3 = "Content/Prefabs/wr2x3.wpref";
            
            /// <summary> Path to Content/Prefabs/wr3x1.wpref </summary>
            public const string wr3x1 = "Content/Prefabs/wr3x1.wpref";
            
            /// <summary> Path to Content/Prefabs/wr3x2.wpref </summary>
            public const string wr3x2 = "Content/Prefabs/wr3x2.wpref";
            
            /// <summary> Path to Content/Prefabs/wt1x1.wpref </summary>
            public const string wt1x1 = "Content/Prefabs/wt1x1.wpref";
            
            /// <summary> Path to Content/Prefabs/wt2x1.wpref </summary>
            public const string wt2x1 = "Content/Prefabs/wt2x1.wpref";
            
            public sealed class Boulders
            {
                
                /// <summary> Path to Content/Prefabs/Boulders/Barney.wpref </summary>
                public const string Barney = "Content/Prefabs/Boulders/Barney.wpref";
                
                /// <summary> Path to Content/Prefabs/Boulders/Farney.wpref </summary>
                public const string Farney = "Content/Prefabs/Boulders/Farney.wpref";
                
                /// <summary> Path to Content/Prefabs/Boulders/Puddin.wpref </summary>
                public const string Puddin = "Content/Prefabs/Boulders/Puddin.wpref";
            }
            
            public sealed class Elements
            {
                
                /// <summary> Path to Content/Prefabs/Elements/cloud01.wpref </summary>
                public const string cloud01 = "Content/Prefabs/Elements/cloud01.wpref";
                
                /// <summary> Path to Content/Prefabs/Elements/cloud02.wpref </summary>
                public const string cloud02 = "Content/Prefabs/Elements/cloud02.wpref";
                
                /// <summary> Path to Content/Prefabs/Elements/cloud03.wpref </summary>
                public const string cloud03 = "Content/Prefabs/Elements/cloud03.wpref";
            }
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/InitialScene.wscene </summary>
            public const string InitialScene = "Content/Scenes/InitialScene.wscene";
            
            /// <summary> Path to Content/Scenes/LevelSelectionScene.wscene </summary>
            public const string LevelSelectionScene = "Content/Scenes/LevelSelectionScene.wscene";
            
            /// <summary> Path to Content/Scenes/MenuScene.wscene </summary>
            public const string MenuScene = "Content/Scenes/MenuScene.wscene";
            
            /// <summary> Path to Content/Scenes/ScoreScene.wscene </summary>
            public const string ScoreScene = "Content/Scenes/ScoreScene.wscene";
            
            public sealed class Backgrounds
            {
                
                /// <summary> Path to Content/Scenes/Backgrounds/Background1.wscene </summary>
                public const string Background1 = "Content/Scenes/Backgrounds/Background1.wscene";
            }
            
            public sealed class Foregrounds
            {
                
                /// <summary> Path to Content/Scenes/Foregrounds/FrontScene.wscene </summary>
                public const string FrontScene = "Content/Scenes/Foregrounds/FrontScene.wscene";
            }
            
            public sealed class Levels
            {
                
                /// <summary> Path to Content/Scenes/Levels/Level1.wscene </summary>
                public const string Level1 = "Content/Scenes/Levels/Level1.wscene";
                
                /// <summary> Path to Content/Scenes/Levels/Level2.wscene </summary>
                public const string Level2 = "Content/Scenes/Levels/Level2.wscene";
                
                /// <summary> Path to Content/Scenes/Levels/Level3.wscene </summary>
                public const string Level3 = "Content/Scenes/Levels/Level3.wscene";
                
                /// <summary> Path to Content/Scenes/Levels/TestLevel.wscene </summary>
                public const string TestLevel = "Content/Scenes/Levels/TestLevel.wscene";
            }
        }
        
        public sealed class Materials
        {
            
            /// <summary> Path to Content/Materials/BackgroundMenuMaterial.wmat </summary>
            public const string BackgroundMenuMaterial = "Content/Materials/BackgroundMenuMaterial.wmat";
            
            /// <summary> Path to Content/Materials/ElasticMaterial.wmat </summary>
            public const string ElasticMaterial = "Content/Materials/ElasticMaterial.wmat";
            
            /// <summary> Path to Content/Materials/SmokeMaterial.wmat </summary>
            public const string SmokeMaterial = "Content/Materials/SmokeMaterial.wmat";
            
            /// <summary> Path to Content/Materials/SnowMaterial.wmat </summary>
            public const string SnowMaterial = "Content/Materials/SnowMaterial.wmat";
            
            /// <summary> Path to Content/Materials/TrajectoryMaterial.wmat </summary>
            public const string TrajectoryMaterial = "Content/Materials/TrajectoryMaterial.wmat";
        }
    }
}
