//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 8/29/2016 9:40:05 AM
namespace OrbitRabbits
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        public sealed class Assets
        {
            
            public sealed class Fonts
            {
                
                /// <summary> Path to Content/Assets/Fonts/OCR A Extended_16.TTF </summary>
                public const string OCR_A_Extended_16_TTF = "Content/Assets/Fonts/OCR A Extended_16.TTF";
            }
            
            public sealed class Sounds
            {
                
                /// <summary> Path to Content/Assets/Sounds/bg_music.mp3 </summary>
                public const string bg_music_mp3 = "Content/Assets/Sounds/bg_music.mp3";
                
                /// <summary> Path to Content/Assets/Sounds/brokenGlass.wav </summary>
                public const string brokenGlass_wav = "Content/Assets/Sounds/brokenGlass.wav";
                
                /// <summary> Path to Content/Assets/Sounds/click.wav </summary>
                public const string click_wav = "Content/Assets/Sounds/click.wav";
                
                /// <summary> Path to Content/Assets/Sounds/explosion.wav </summary>
                public const string explosion_wav = "Content/Assets/Sounds/explosion.wav";
                
                /// <summary> Path to Content/Assets/Sounds/fall.wav </summary>
                public const string fall_wav = "Content/Assets/Sounds/fall.wav";
                
                /// <summary> Path to Content/Assets/Sounds/impulse.wav </summary>
                public const string impulse_wav = "Content/Assets/Sounds/impulse.wav";
                
                /// <summary> Path to Content/Assets/Sounds/start.wav </summary>
                public const string start_wav = "Content/Assets/Sounds/start.wav";
            }
            
            public sealed class Textures
            {
                
                /// <summary> Path to Content/Assets/Textures/background.png </summary>
                public const string background_png = "Content/Assets/Textures/background.png";
                
                /// <summary> Path to Content/Assets/Textures/game.spritesheet </summary>
                public const string game_spritesheet = "Content/Assets/Textures/game.spritesheet";
                
                /// <summary> Path to Content/Assets/Textures/largeLogo.png </summary>
                public const string largeLogo_png = "Content/Assets/Textures/largeLogo.png";
                
                /// <summary> Path to Content/Assets/Textures/moonPressed.png </summary>
                public const string moonPressed_png = "Content/Assets/Textures/moonPressed.png";
                
                /// <summary> Path to Content/Assets/Textures/moonRelease.png </summary>
                public const string moonRelease_png = "Content/Assets/Textures/moonRelease.png";
                
                /// <summary> Path to Content/Assets/Textures/restartPressed.png </summary>
                public const string restartPressed_png = "Content/Assets/Textures/restartPressed.png";
                
                /// <summary> Path to Content/Assets/Textures/restartRelease.png </summary>
                public const string restartRelease_png = "Content/Assets/Textures/restartRelease.png";
                
                /// <summary> Path to Content/Assets/Textures/scorePanel.png </summary>
                public const string scorePanel_png = "Content/Assets/Textures/scorePanel.png";
                
                /// <summary> Path to Content/Assets/Textures/starParticle.png </summary>
                public const string starParticle_png = "Content/Assets/Textures/starParticle.png";
                
                /// <summary> Texture names from spritesheet Content/Assets/Textures/game.spritesheet </summary>
                public struct game_spritesheet_TextureName
                {
                    
                    public const string earth = "earth";
                    
                    public const string gravity = "gravity";
                    
                    public const string moonBack = "moonBack";
                    
                    public const string rabbit = "rabbit";
                    
                    public const string smallLogo = "smallLogo";
                    
                    public const string tapHand = "tapHand";
                    
                    public const string waveLogo = "waveLogo";
                    
                    public const string sun = "sun";
                }
            }
            
            public sealed class Materials
            {
                
                /// <summary> Path to Content/Assets/Materials/StarParticleMaterial.wmat </summary>
                public const string StarParticleMaterial = "Content/Assets/Materials/StarParticleMaterial.wmat";
            }
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/GamePlayScene.wscene </summary>
            public const string GamePlayScene = "Content/Scenes/GamePlayScene.wscene";
            
            /// <summary> Path to Content/Scenes/MainMenuScene.wscene </summary>
            public const string MainMenuScene = "Content/Scenes/MainMenuScene.wscene";
        }
    }
}
