//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 2/17/2016 3:44:31 PM
namespace DeepSpace
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        public sealed class Assets
        {
            
            /// <summary> Path to Content/Assets/BestScore.png </summary>
            public const string BestScore_png = "Content/Assets/BestScore.png";
            
            /// <summary> Path to Content/Assets/bg_planets.PNG </summary>
            public const string bg_planets_PNG = "Content/Assets/bg_planets.PNG";
            
            /// <summary> Path to Content/Assets/bg_space.PNG </summary>
            public const string bg_space_PNG = "Content/Assets/bg_space.PNG";
            
            /// <summary> Path to Content/Assets/blast0.wav </summary>
            public const string blast0_wav = "Content/Assets/blast0.wav";
            
            /// <summary> Path to Content/Assets/blast1.wav </summary>
            public const string blast1_wav = "Content/Assets/blast1.wav";
            
            /// <summary> Path to Content/Assets/blast2.wav </summary>
            public const string blast2_wav = "Content/Assets/blast2.wav";
            
            /// <summary> Path to Content/Assets/Bullet.png </summary>
            public const string Bullet_png = "Content/Assets/Bullet.png";
            
            /// <summary> Path to Content/Assets/BulletCollider.png </summary>
            public const string BulletCollider_png = "Content/Assets/BulletCollider.png";
            
            /// <summary> Path to Content/Assets/DeepSpace_logo.PNG </summary>
            public const string DeepSpace_logo_PNG = "Content/Assets/DeepSpace_logo.PNG";
            
            /// <summary> Path to Content/Assets/Enemy.PNG </summary>
            public const string Enemy_PNG = "Content/Assets/Enemy.PNG";
            
            /// <summary> Path to Content/Assets/EnemyBullet.png </summary>
            public const string EnemyBullet_png = "Content/Assets/EnemyBullet.png";
            
            /// <summary> Path to Content/Assets/EnemyBulletCollider.png </summary>
            public const string EnemyBulletCollider_png = "Content/Assets/EnemyBulletCollider.png";
            
            /// <summary> Path to Content/Assets/EnemyCollider.PNG </summary>
            public const string EnemyCollider_PNG = "Content/Assets/EnemyCollider.PNG";
            
            /// <summary> Path to Content/Assets/explode0.wav </summary>
            public const string explode0_wav = "Content/Assets/explode0.wav";
            
            /// <summary> Path to Content/Assets/explode1.wav </summary>
            public const string explode1_wav = "Content/Assets/explode1.wav";
            
            /// <summary> Path to Content/Assets/explode2.wav </summary>
            public const string explode2_wav = "Content/Assets/explode2.wav";
            
            /// <summary> Path to Content/Assets/ExplodeSprite.spritesheet </summary>
            public const string ExplodeSprite_spritesheet = "Content/Assets/ExplodeSprite.spritesheet";
            
            /// <summary> Path to Content/Assets/GameOver.png </summary>
            public const string GameOver_png = "Content/Assets/GameOver.png";
            
            /// <summary> Path to Content/Assets/joystickBackground.png </summary>
            public const string joystickBackground_png = "Content/Assets/joystickBackground.png";
            
            /// <summary> Path to Content/Assets/joystickThumb.png </summary>
            public const string joystickThumb_png = "Content/Assets/joystickThumb.png";
            
            /// <summary> Path to Content/Assets/Player.png </summary>
            public const string Player_png = "Content/Assets/Player.png";
            
            /// <summary> Path to Content/Assets/PlayerCollider.png </summary>
            public const string PlayerCollider_png = "Content/Assets/PlayerCollider.png";
            
            /// <summary> Path to Content/Assets/PressStart.PNG </summary>
            public const string PressStart_PNG = "Content/Assets/PressStart.PNG";
            
            /// <summary> Path to Content/Assets/restart.png </summary>
            public const string restart_png = "Content/Assets/restart.png";
            
            /// <summary> Path to Content/Assets/score.png </summary>
            public const string score_png = "Content/Assets/score.png";
            
            /// <summary> Path to Content/Assets/Star.jpg </summary>
            public const string Star_jpg = "Content/Assets/Star.jpg";
            
            /// <summary> Texture names from spritesheet Content/Assets/ExplodeSprite.spritesheet </summary>
            public struct ExplodeSprite_spritesheet_TextureName
            {
                
                public const string explode0 = "explode0";
                
                public const string explode1 = "explode1";
                
                public const string explode2 = "explode2";
                
                public const string explode3 = "explode3";
                
                public const string explode4 = "explode4";
                
                public const string explode5 = "explode5";
                
                public const string explode6 = "explode6";
                
                public const string explode7 = "explode7";
                
                public const string explode8 = "explode8";
            }
        }
        
        public sealed class Fonts
        {
            
            /// <summary> Path to Content/Fonts/Space Age.TTF </summary>
            public const string Space_Age_TTF = "Content/Fonts/Space Age.TTF";
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/GameOverScene.wscene </summary>
            public const string GameOverScene = "Content/Scenes/GameOverScene.wscene";
            
            /// <summary> Path to Content/Scenes/GamePlayScene.wscene </summary>
            public const string GamePlayScene = "Content/Scenes/GamePlayScene.wscene";
            
            /// <summary> Path to Content/Scenes/IntroScene.wscene </summary>
            public const string IntroScene = "Content/Scenes/IntroScene.wscene";
        }
    }
}
