//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 9/5/2016 11:04:01 AM
namespace SurvivorNinja
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        public sealed class Assets
        {
            
            public sealed class Fonts
            {
                
                /// <summary> Path to Content/Assets/Fonts/Coalition_16.ttf </summary>
                public const string Coalition_16_ttf = "Content/Assets/Fonts/Coalition_16.ttf";
            }
            
            public sealed class Sounds
            {
                
                /// <summary> Path to Content/Assets/Sounds/enemyDead.wav </summary>
                public const string enemyDead_wav = "Content/Assets/Sounds/enemyDead.wav";
                
                /// <summary> Path to Content/Assets/Sounds/gameOver.wav </summary>
                public const string gameOver_wav = "Content/Assets/Sounds/gameOver.wav";
                
                /// <summary> Path to Content/Assets/Sounds/impact.wav </summary>
                public const string impact_wav = "Content/Assets/Sounds/impact.wav";
                
                /// <summary> Path to Content/Assets/Sounds/ninjaMusic.mp3 </summary>
                public const string ninjaMusic_mp3 = "Content/Assets/Sounds/ninjaMusic.mp3";
                
                /// <summary> Path to Content/Assets/Sounds/playerHurt.wav </summary>
                public const string playerHurt_wav = "Content/Assets/Sounds/playerHurt.wav";
                
                /// <summary> Path to Content/Assets/Sounds/ready.wav </summary>
                public const string ready_wav = "Content/Assets/Sounds/ready.wav";
                
                /// <summary> Path to Content/Assets/Sounds/shoot.wav </summary>
                public const string shoot_wav = "Content/Assets/Sounds/shoot.wav";
            }
            
            public sealed class Textures
            {
                
                /// <summary> Path to Content/Assets/Textures/background.png </summary>
                public const string background_png = "Content/Assets/Textures/background.png";
                
                /// <summary> Path to Content/Assets/Textures/bullet.png </summary>
                public const string bullet_png = "Content/Assets/Textures/bullet.png";
                
                /// <summary> Path to Content/Assets/Textures/enemy.png </summary>
                public const string enemy_png = "Content/Assets/Textures/enemy.png";
                
                /// <summary> Path to Content/Assets/Textures/gameover.png </summary>
                public const string gameover_png = "Content/Assets/Textures/gameover.png";
                
                /// <summary> Path to Content/Assets/Textures/hubBackground.png </summary>
                public const string hubBackground_png = "Content/Assets/Textures/hubBackground.png";
                
                /// <summary> Path to Content/Assets/Textures/joystickBackground.png </summary>
                public const string joystickBackground_png = "Content/Assets/Textures/joystickBackground.png";
                
                /// <summary> Path to Content/Assets/Textures/joystickThumb.png </summary>
                public const string joystickThumb_png = "Content/Assets/Textures/joystickThumb.png";
                
                /// <summary> Path to Content/Assets/Textures/logo.png </summary>
                public const string logo_png = "Content/Assets/Textures/logo.png";
                
                /// <summary> Path to Content/Assets/Textures/player.png </summary>
                public const string player_png = "Content/Assets/Textures/player.png";
                
                /// <summary> Path to Content/Assets/Textures/tap_to_start.png </summary>
                public const string tap_to_start_png = "Content/Assets/Textures/tap_to_start.png";
            }
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/GamePlayScene.wscene </summary>
            public const string GamePlayScene = "Content/Scenes/GamePlayScene.wscene";
        }
    }
}
