// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

// File generated on 05/09/2016 8:55:05
namespace FlyingKite
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        public sealed class Assets
        {
            
            public sealed class Audio
            {
                
                /// <summary> Path to Content/Assets/Audio/bg_music.mp3 </summary>
                public const string bg_music_mp3 = "Content/Assets/Audio/bg_music.mp3";
                
                /// <summary> Path to Content/Assets/Audio/chop1.wav </summary>
                public const string chop1_wav = "Content/Assets/Audio/chop1.wav";
                
                /// <summary> Path to Content/Assets/Audio/chop2.wav </summary>
                public const string chop2_wav = "Content/Assets/Audio/chop2.wav";
                
                /// <summary> Path to Content/Assets/Audio/coin.wav </summary>
                public const string coin_wav = "Content/Assets/Audio/coin.wav";
                
                /// <summary> Path to Content/Assets/Audio/crash.wav </summary>
                public const string crash_wav = "Content/Assets/Audio/crash.wav";
            }
            
            public sealed class Fonts
            {
                
                /// <summary> Path to Content/Assets/Fonts/BadaBoom BB.wpk </summary>
                public const string BadaBoom_BB_wpk = "Content/Assets/Fonts/BadaBoom BB.wpk";
                
                /// <summary> Path to Content/Assets/Fonts/Showcard Gothic.wpk </summary>
                public const string Showcard_Gothic_wpk = "Content/Assets/Fonts/Showcard Gothic.wpk";
            }
            
            public sealed class Gameplay
            {
                
                /// <summary> Path to Content/Assets/Gameplay/Game.spritesheet </summary>
                public const string Game_spritesheet = "Content/Assets/Gameplay/Game.spritesheet";
                
                /// <summary> Path to Content/Assets/Gameplay/bg.png </summary>
                public const string bg_png = "Content/Assets/Gameplay/bg.png";
                
                /// <summary> Path to Content/Assets/Gameplay/kite_anims.spritesheet </summary>
                public const string kite_anims_spritesheet = "Content/Assets/Gameplay/kite_anims.spritesheet";
                
                /// <summary> Path to Content/Assets/Gameplay/kite_rope_3x1.png </summary>
                public const string kite_rope_3x1_png = "Content/Assets/Gameplay/kite_rope_3x1.png";
                
                /// <summary> Path to Content/Assets/Gameplay/white_pixel.png </summary>
                public const string white_pixel_png = "Content/Assets/Gameplay/white_pixel.png";
                
                /// <summary> Texture names from spritesheet Content/Assets/Gameplay/Game.spritesheet </summary>
                public struct Game_spritesheet_TextureName
                {
                    
                    public const string bg_cloud = "bg_cloud";
                    
                    public const string bg_fish_kite_01 = "bg_fish_kite_01";
                    
                    public const string bg_fish_kite_02 = "bg_fish_kite_02";
                    
                    public const string bg_plane = "bg_plane";
                    
                    public const string kite_ball = "kite_ball";
                    
                    public const string obstacle_bottom = "obstacle_bottom";
                    
                    public const string obstacle_top = "obstacle_top";
                }
                
                /// <summary> Texture names from spritesheet Content/Assets/Gameplay/kite_anims.spritesheet </summary>
                public struct kite_anims_spritesheet_TextureName
                {
                    
                    public const string fish_blue_kite_01 = "fish_blue_kite_01";
                    
                    public const string fish_blue_kite_02 = "fish_blue_kite_02";
                    
                    public const string fish_blue_kite_03 = "fish_blue_kite_03";
                    
                    public const string fish_blue_kite_04 = "fish_blue_kite_04";
                    
                    public const string fish_blue_kite_05 = "fish_blue_kite_05";
                    
                    public const string fish_blue_kite_06 = "fish_blue_kite_06";
                    
                    public const string fish_blue_kite_07 = "fish_blue_kite_07";
                    
                    public const string fish_blue_kite_08 = "fish_blue_kite_08";
                    
                    public const string fish_blue_kite_09 = "fish_blue_kite_09";
                    
                    public const string fish_green_kite_01 = "fish_green_kite_01";
                    
                    public const string fish_green_kite_02 = "fish_green_kite_02";
                    
                    public const string fish_green_kite_03 = "fish_green_kite_03";
                    
                    public const string fish_green_kite_04 = "fish_green_kite_04";
                    
                    public const string fish_green_kite_05 = "fish_green_kite_05";
                    
                    public const string fish_green_kite_06 = "fish_green_kite_06";
                    
                    public const string fish_green_kite_07 = "fish_green_kite_07";
                    
                    public const string fish_green_kite_08 = "fish_green_kite_08";
                    
                    public const string fish_green_kite_09 = "fish_green_kite_09";
                    
                    public const string fish_orange_kite_01 = "fish_orange_kite_01";
                    
                    public const string fish_orange_kite_02 = "fish_orange_kite_02";
                    
                    public const string fish_orange_kite_03 = "fish_orange_kite_03";
                    
                    public const string fish_orange_kite_04 = "fish_orange_kite_04";
                    
                    public const string fish_orange_kite_05 = "fish_orange_kite_05";
                    
                    public const string fish_orange_kite_06 = "fish_orange_kite_06";
                    
                    public const string fish_orange_kite_07 = "fish_orange_kite_07";
                    
                    public const string fish_orange_kite_08 = "fish_orange_kite_08";
                    
                    public const string fish_orange_kite_09 = "fish_orange_kite_09";
                }
                
                public sealed class PixelCollider
                {
                    
                    /// <summary> Path to Content/Assets/Gameplay/PixelCollider/fish_kite.png </summary>
                    public const string fish_kite_png = "Content/Assets/Gameplay/PixelCollider/fish_kite.png";
                    
                    /// <summary> Path to Content/Assets/Gameplay/PixelCollider/obstacle_bottom.png </summary>
                    public const string obstacle_bottom_png = "Content/Assets/Gameplay/PixelCollider/obstacle_bottom.png";
                    
                    /// <summary> Path to Content/Assets/Gameplay/PixelCollider/obstacle_top.png </summary>
                    public const string obstacle_top_png = "Content/Assets/Gameplay/PixelCollider/obstacle_top.png";
                }
                
                public sealed class Materials
                {
                    
                    /// <summary> Path to Content/Assets/Gameplay/Materials/KiteRopeMaterial.wmat </summary>
                    public const string KiteRopeMaterial = "Content/Assets/Gameplay/Materials/KiteRopeMaterial.wmat";
                    
                    /// <summary> Path to Content/Assets/Gameplay/Materials/StarMaterial.wmat </summary>
                    public const string StarMaterial = "Content/Assets/Gameplay/Materials/StarMaterial.wmat";
                }
            }
            
            public sealed class Menus
            {
                
                /// <summary> Path to Content/Assets/Menus/best_score.png </summary>
                public const string best_score_png = "Content/Assets/Menus/best_score.png";
                
                /// <summary> Path to Content/Assets/Menus/bg_gameover.png </summary>
                public const string bg_gameover_png = "Content/Assets/Menus/bg_gameover.png";
                
                /// <summary> Path to Content/Assets/Menus/gameover.png </summary>
                public const string gameover_png = "Content/Assets/Menus/gameover.png";
                
                /// <summary> Path to Content/Assets/Menus/logo.png </summary>
                public const string logo_png = "Content/Assets/Menus/logo.png";
                
                /// <summary> Path to Content/Assets/Menus/play_button.png </summary>
                public const string play_button_png = "Content/Assets/Menus/play_button.png";
                
                /// <summary> Path to Content/Assets/Menus/play_button_pressed.png </summary>
                public const string play_button_pressed_png = "Content/Assets/Menus/play_button_pressed.png";
                
                /// <summary> Path to Content/Assets/Menus/star.png </summary>
                public const string star_png = "Content/Assets/Menus/star.png";
            }
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/GameOverScene.wscene </summary>
            public const string GameOverScene = "Content/Scenes/GameOverScene.wscene";
            
            /// <summary> Path to Content/Scenes/GameScene.wscene </summary>
            public const string GameScene = "Content/Scenes/GameScene.wscene";
            
            /// <summary> Path to Content/Scenes/MenuScene.wscene </summary>
            public const string MenuScene = "Content/Scenes/MenuScene.wscene";
        }
    }
}
