//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 05/07/2018 12:14:35
namespace Match3
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        /// <summary> Path to Content/Match3.wgame </summary>
        public const string GameInfo = "Content/Match3.wgame";
        
        public sealed class Assets
        {
            
            public sealed class Audio
            {
                
                /// <summary> Path to Content/Assets/Audio/bgMusic.mp3 </summary>
                public const string bgMusic_mp3 = "Content/Assets/Audio/bgMusic.mp3";
                
                /// <summary> Path to Content/Assets/Audio/Button.wav </summary>
                public const string Button_wav = "Content/Assets/Audio/Button.wav";
                
                /// <summary> Path to Content/Assets/Audio/CandyBoom.wav </summary>
                public const string CandyBoom_wav = "Content/Assets/Audio/CandyBoom.wav";
                
                /// <summary> Path to Content/Assets/Audio/ComboAppear.wav </summary>
                public const string ComboAppear_wav = "Content/Assets/Audio/ComboAppear.wav";
                
                /// <summary> Path to Content/Assets/Audio/ComboAppear2.wav </summary>
                public const string ComboAppear2_wav = "Content/Assets/Audio/ComboAppear2.wav";
                
                /// <summary> Path to Content/Assets/Audio/Countdown.wav </summary>
                public const string Countdown_wav = "Content/Assets/Audio/Countdown.wav";
                
                /// <summary> Path to Content/Assets/Audio/InvalidMovement.wav </summary>
                public const string InvalidMovement_wav = "Content/Assets/Audio/InvalidMovement.wav";
                
                /// <summary> Path to Content/Assets/Audio/ValidMovement.wav </summary>
                public const string ValidMovement_wav = "Content/Assets/Audio/ValidMovement.wav";
            }
            
            public sealed class Fonts
            {
                
                /// <summary> Path to Content/Assets/Fonts/BradyBunchMedium.ttf </summary>
                public const string BradyBunchMedium_ttf = "Content/Assets/Fonts/BradyBunchMedium.ttf";
            }
            
            public sealed class GUI
            {
                
                /// <summary> Path to Content/Assets/GUI/BackgroundElems.spritesheet </summary>
                public const string BackgroundElems_spritesheet = "Content/Assets/GUI/BackgroundElems.spritesheet";
                
                /// <summary> Path to Content/Assets/GUI/Buttons.spritesheet </summary>
                public const string Buttons_spritesheet = "Content/Assets/GUI/Buttons.spritesheet";
                
                /// <summary> Path to Content/Assets/GUI/Candies.spritesheet </summary>
                public const string Candies_spritesheet = "Content/Assets/GUI/Candies.spritesheet";
                
                /// <summary> Path to Content/Assets/GUI/Logo.png </summary>
                public const string Logo_png = "Content/Assets/GUI/Logo.png";
                
                /// <summary> Path to Content/Assets/GUI/Panels.spritesheet </summary>
                public const string Panels_spritesheet = "Content/Assets/GUI/Panels.spritesheet";
                
                /// <summary> Path to Content/Assets/GUI/WhitePixel.png </summary>
                public const string WhitePixel_png = "Content/Assets/GUI/WhitePixel.png";
                
                /// <summary> Texture names from spritesheet Content/Assets/GUI/BackgroundElems.spritesheet </summary>
                public struct BackgroundElems_spritesheet_TextureName
                {
                    
                    public const string Cross = "Cross";
                    
                    public const string Home = "Home";
                    
                    public const string Shield = "Shield";
                    
                    public const string Stars = "Stars";
                    
                    public const string Trophy = "Trophy";
                }
                
                /// <summary> Texture names from spritesheet Content/Assets/GUI/Buttons.spritesheet </summary>
                public struct Buttons_spritesheet_TextureName
                {
                    
                    public const string BgBlueButton = "BgBlueButton";
                    
                    public const string BgRedButton = "BgRedButton";
                    
                    public const string BgButtonPressed = "BgButtonPressed";
                    
                    public const string Info = "Info";
                    
                    public const string InfoPressed = "InfoPressed";
                    
                    public const string SoundOn = "SoundOn";
                    
                    public const string SoundOff = "SoundOff";
                    
                    public const string BgBlueSquareButton = "BgBlueSquareButton";
                    
                    public const string BgSquarePressed = "BgSquarePressed";
                    
                    public const string BgRedSquareButton = "BgRedSquareButton";
                    
                    public const string Back = "Back";
                    
                    public const string BackPressed = "BackPressed";
                    
                    public const string LockedButton = "LockedButton";
                    
                    public const string Pause = "Pause";
                    
                    public const string PausePressed = "PausePressed";
                    
                    public const string Play = "Play";
                    
                    public const string PlayPressed = "PlayPressed";
                    
                    public const string Levels = "Levels";
                    
                    public const string LevelsPressed = "LevelsPressed";
                    
                    public const string Home = "Home";
                    
                    public const string HomePressed = "HomePressed";
                    
                    public const string Cancel = "Cancel";
                    
                    public const string CancelPressed = "CancelPressed";
                    
                    public const string Ok = "Ok";
                    
                    public const string OkPressed = "OkPressed";
                    
                    public const string Reset = "Reset";
                    
                    public const string ResetPressed = "ResetPressed";
                }
                
                /// <summary> Texture names from spritesheet Content/Assets/GUI/Candies.spritesheet </summary>
                public struct Candies_spritesheet_TextureName
                {
                    
                    public const string bean_blue = "bean_blue";
                    
                    public const string bean_green = "bean_green";
                    
                    public const string bean_red = "bean_red";
                    
                    public const string bean_yellow = "bean_yellow";
                    
                    public const string jelly_blue = "jelly_blue";
                    
                    public const string jelly_green = "jelly_green";
                    
                    public const string jelly_red = "jelly_red";
                    
                    public const string jelly_yellow = "jelly_yellow";
                    
                    public const string lollipop_blue = "lollipop_blue";
                    
                    public const string lollipop_green = "lollipop_green";
                    
                    public const string lollipop_red = "lollipop_red";
                    
                    public const string lollipop_yellow = "lollipop_yellow";
                    
                    public const string wrappedsolid_blue = "wrappedsolid_blue";
                    
                    public const string wrappedsolid_green = "wrappedsolid_green";
                    
                    public const string wrappedsolid_red = "wrappedsolid_red";
                    
                    public const string wrappedsolid_yellow = "wrappedsolid_yellow";
                    
                    public const string wrappedtrans_blue = "wrappedtrans_blue";
                    
                    public const string wrappedtrans_green = "wrappedtrans_green";
                    
                    public const string wrappedtrans_red = "wrappedtrans_red";
                    
                    public const string wrappedtrans_yellow = "wrappedtrans_yellow";
                    
                    public const string explosionblue01 = "explosionblue01";
                    
                    public const string explosionblue02 = "explosionblue02";
                    
                    public const string explosionblue03 = "explosionblue03";
                    
                    public const string explosionblue04 = "explosionblue04";
                    
                    public const string explosionblue05 = "explosionblue05";
                    
                    public const string explosiongreen01 = "explosiongreen01";
                    
                    public const string explosiongreen02 = "explosiongreen02";
                    
                    public const string explosiongreen03 = "explosiongreen03";
                    
                    public const string explosiongreen04 = "explosiongreen04";
                    
                    public const string explosiongreen05 = "explosiongreen05";
                    
                    public const string explosionpink01 = "explosionpink01";
                    
                    public const string explosionpink02 = "explosionpink02";
                    
                    public const string explosionpink03 = "explosionpink03";
                    
                    public const string explosionpink04 = "explosionpink04";
                    
                    public const string explosionpink05 = "explosionpink05";
                }
                
                /// <summary> Texture names from spritesheet Content/Assets/GUI/Panels.spritesheet </summary>
                public struct Panels_spritesheet_TextureName
                {
                    
                    public const string PanelBg1 = "PanelBg1";
                    
                    public const string PanelBg2 = "PanelBg2";
                    
                    public const string PanelBg3 = "PanelBg3";
                    
                    public const string PanelBg4 = "PanelBg4";
                    
                    public const string PanelBg5 = "PanelBg5";
                    
                    public const string PanelBgSlice = "PanelBgSlice";
                    
                    public const string Slice = "Slice";
                    
                    public const string SignBg = "SignBg";
                    
                    public const string StarSmallColor = "StarSmallColor";
                    
                    public const string StarSmallGray = "StarSmallGray";
                    
                    public const string StarMediumColor = "StarMediumColor";
                    
                    public const string StarMediumGray = "StarMediumGray";
                    
                    public const string Clock = "Clock";
                    
                    public const string StarEmpty = "StarEmpty";
                    
                    public const string StarBigColor = "StarBigColor";
                }
                
                public sealed class Panels
                {
                    
                    /// <summary> Path to Content/Assets/GUI/Panels/PanelBg1.9.png </summary>
                    public const string PanelBg1_9_png = "Content/Assets/GUI/Panels/PanelBg1.9.png";
                    
                    /// <summary> Path to Content/Assets/GUI/Panels/PanelBg2.9.png </summary>
                    public const string PanelBg2_9_png = "Content/Assets/GUI/Panels/PanelBg2.9.png";
                    
                    /// <summary> Path to Content/Assets/GUI/Panels/PanelBg3.9.png </summary>
                    public const string PanelBg3_9_png = "Content/Assets/GUI/Panels/PanelBg3.9.png";
                    
                    /// <summary> Path to Content/Assets/GUI/Panels/PanelBg4.9.png </summary>
                    public const string PanelBg4_9_png = "Content/Assets/GUI/Panels/PanelBg4.9.png";
                    
                    /// <summary> Path to Content/Assets/GUI/Panels/PanelBg5.9.png </summary>
                    public const string PanelBg5_9_png = "Content/Assets/GUI/Panels/PanelBg5.9.png";
                    
                    /// <summary> Path to Content/Assets/GUI/Panels/PanelBgSlice.9.png </summary>
                    public const string PanelBgSlice_9_png = "Content/Assets/GUI/Panels/PanelBgSlice.9.png";
                    
                    /// <summary> Path to Content/Assets/GUI/Panels/Slice.9.png </summary>
                    public const string Slice_9_png = "Content/Assets/GUI/Panels/Slice.9.png";
                }
            }
            
            public sealed class Textures
            {
                
                /// <summary> Path to Content/Assets/Textures/WAVE_logo.png </summary>
                public const string WAVE_logo_png = "Content/Assets/Textures/WAVE_logo.png";
            }
        }
        
        public sealed class Prefabs
        {
            
            public sealed class Buttons
            {
                
                /// <summary> Path to Content/Prefabs/Buttons/LevelBtn.wpref </summary>
                public const string LevelBtn = "Content/Prefabs/Buttons/LevelBtn.wpref";
                
                /// <summary> Path to Content/Prefabs/Buttons/NavSquaredBtn.wpref </summary>
                public const string NavSquaredBtn = "Content/Prefabs/Buttons/NavSquaredBtn.wpref";
            }
            
            public sealed class Gameplay
            {
                
                /// <summary> Path to Content/Prefabs/Gameplay/Candy.wpref </summary>
                public const string Candy = "Content/Prefabs/Gameplay/Candy.wpref";
            }
            
            public sealed class Panels
            {
                
                /// <summary> Path to Content/Prefabs/Panels/FillStar.wpref </summary>
                public const string FillStar = "Content/Prefabs/Panels/FillStar.wpref";
            }
        }
        
        public sealed class RenderLayers
        {
            
            /// <summary>Id of Opaque</summary>
            public const int Opaque = 0;
            
            /// <summary>Id of Skybox</summary>
            public const int Skybox = 1;
            
            /// <summary>Id of Alpha</summary>
            public const int Alpha = 2;
            
            /// <summary>Id of Additive</summary>
            public const int Additive = 3;
            
            /// <summary>Id of GUI</summary>
            public const int GUI = 4;
            
            /// <summary>Id of Debug</summary>
            public const int Debug = 5;
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/About.wscene </summary>
            public const string About = "Content/Scenes/About.wscene";
            
            /// <summary> Path to Content/Scenes/ExitConfirmation.wscene </summary>
            public const string ExitConfirmation = "Content/Scenes/ExitConfirmation.wscene";
            
            /// <summary> Path to Content/Scenes/Finish.wscene </summary>
            public const string Finish = "Content/Scenes/Finish.wscene";
            
            /// <summary> Path to Content/Scenes/Gameplay.wscene </summary>
            public const string Gameplay = "Content/Scenes/Gameplay.wscene";
            
            /// <summary> Path to Content/Scenes/LevelSelection.wscene </summary>
            public const string LevelSelection = "Content/Scenes/LevelSelection.wscene";
            
            /// <summary> Path to Content/Scenes/Loading.wscene </summary>
            public const string Loading = "Content/Scenes/Loading.wscene";
            
            /// <summary> Path to Content/Scenes/MainMenu.wscene </summary>
            public const string MainMenu = "Content/Scenes/MainMenu.wscene";
            
            /// <summary> Path to Content/Scenes/MenuBackground.wscene </summary>
            public const string MenuBackground = "Content/Scenes/MenuBackground.wscene";
            
            /// <summary> Path to Content/Scenes/Pause.wscene </summary>
            public const string Pause = "Content/Scenes/Pause.wscene";
        }
    }
}
