//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 26/11/2015 19:13:39
namespace SuperSquid
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        public sealed class Assets
        {
            
            public sealed class Fonts
            {
                
                /// <summary> Path to Content/Assets/Fonts/Bulky Pixels_16.TTF </summary>
                public const string Bulky_Pixels_16_TTF = "Content/Assets/Fonts/Bulky Pixels_16.TTF";
                
                /// <summary> Path to Content/Assets/Fonts/Bulky Pixels_26.TTF </summary>
                public const string Bulky_Pixels_26_TTF = "Content/Assets/Fonts/Bulky Pixels_26.TTF";
            }
            
            public sealed class Sounds
            {
                
                /// <summary> Path to Content/Assets/Sounds/bg_music.mp3 </summary>
                public const string bg_music_mp3 = "Content/Assets/Sounds/bg_music.mp3";
                
                /// <summary> Path to Content/Assets/Sounds/jellyCrash.wav </summary>
                public const string jellyCrash_wav = "Content/Assets/Sounds/jellyCrash.wav";
                
                /// <summary> Path to Content/Assets/Sounds/rockCrash.wav </summary>
                public const string rockCrash_wav = "Content/Assets/Sounds/rockCrash.wav";
                
                /// <summary> Path to Content/Assets/Sounds/squid_swim1.wav </summary>
                public const string squid_swim1_wav = "Content/Assets/Sounds/squid_swim1.wav";
                
                /// <summary> Path to Content/Assets/Sounds/squid_swim2.wav </summary>
                public const string squid_swim2_wav = "Content/Assets/Sounds/squid_swim2.wav";
                
                /// <summary> Path to Content/Assets/Sounds/star.wav </summary>
                public const string star_wav = "Content/Assets/Sounds/star.wav";
            }
            
            public sealed class Textures
            {
                
                /// <summary> Path to Content/Assets/Textures/centralRock.png </summary>
                public const string centralRock_png = "Content/Assets/Textures/centralRock.png";
                
                /// <summary> Path to Content/Assets/Textures/centralRockCollider.png </summary>
                public const string centralRockCollider_png = "Content/Assets/Textures/centralRockCollider.png";
                
                /// <summary> Path to Content/Assets/Textures/game.png </summary>
                public const string game_png = "Content/Assets/Textures/game.png";
                
                /// <summary> Path to Content/Assets/Textures/jellyFish.spritesheet </summary>
                public const string jellyFish_spritesheet = "Content/Assets/Textures/jellyFish.spritesheet";
                
                /// <summary> Path to Content/Assets/Textures/jellyFishCollider.png </summary>
                public const string jellyFishCollider_png = "Content/Assets/Textures/jellyFishCollider.png";
                
                /// <summary> Path to Content/Assets/Textures/jellyFishLittle.spritesheet </summary>
                public const string jellyFishLittle_spritesheet = "Content/Assets/Textures/jellyFishLittle.spritesheet";
                
                /// <summary> Path to Content/Assets/Textures/jellyFishLittleCollider.png </summary>
                public const string jellyFishLittleCollider_png = "Content/Assets/Textures/jellyFishLittleCollider.png";
                
                /// <summary> Path to Content/Assets/Textures/leftRock.png </summary>
                public const string leftRock_png = "Content/Assets/Textures/leftRock.png";
                
                /// <summary> Path to Content/Assets/Textures/leftRockCollider.png </summary>
                public const string leftRockCollider_png = "Content/Assets/Textures/leftRockCollider.png";
                
                /// <summary> Path to Content/Assets/Textures/over.png </summary>
                public const string over_png = "Content/Assets/Textures/over.png";
                
                /// <summary> Path to Content/Assets/Textures/play.png </summary>
                public const string play_png = "Content/Assets/Textures/play.png";
                
                /// <summary> Path to Content/Assets/Textures/playPressed.png </summary>
                public const string playPressed_png = "Content/Assets/Textures/playPressed.png";
                
                /// <summary> Path to Content/Assets/Textures/restart.png </summary>
                public const string restart_png = "Content/Assets/Textures/restart.png";
                
                /// <summary> Path to Content/Assets/Textures/restartPressed.png </summary>
                public const string restartPressed_png = "Content/Assets/Textures/restartPressed.png";
                
                /// <summary> Path to Content/Assets/Textures/rightRock.png </summary>
                public const string rightRock_png = "Content/Assets/Textures/rightRock.png";
                
                /// <summary> Path to Content/Assets/Textures/rightRockCollider.png </summary>
                public const string rightRockCollider_png = "Content/Assets/Textures/rightRockCollider.png";
                
                /// <summary> Path to Content/Assets/Textures/seaweeds.spritesheet </summary>
                public const string seaweeds_spritesheet = "Content/Assets/Textures/seaweeds.spritesheet";
                
                /// <summary> Path to Content/Assets/Textures/squid.png </summary>
                public const string squid_png = "Content/Assets/Textures/squid.png";
                
                /// <summary> Path to Content/Assets/Textures/squidCollider.png </summary>
                public const string squidCollider_png = "Content/Assets/Textures/squidCollider.png";
                
                /// <summary> Path to Content/Assets/Textures/squiddd.spritesheet </summary>
                public const string squiddd_spritesheet = "Content/Assets/Textures/squiddd.spritesheet";
                
                /// <summary> Path to Content/Assets/Textures/starfish.png </summary>
                public const string starfish_png = "Content/Assets/Textures/starfish.png";
                
                /// <summary> Path to Content/Assets/Textures/super.png </summary>
                public const string super_png = "Content/Assets/Textures/super.png";
                
                /// <summary> Path to Content/Assets/Textures/waterParticle.png </summary>
                public const string waterParticle_png = "Content/Assets/Textures/waterParticle.png";
                
                /// <summary> Path to Content/Assets/Textures/waterParticle2.png </summary>
                public const string waterParticle2_png = "Content/Assets/Textures/waterParticle2.png";
                
                /// <summary> Path to Content/Assets/Textures/WhitePixel.png </summary>
                public const string WhitePixel_png = "Content/Assets/Textures/WhitePixel.png";
                
                /// <summary> Texture names from spritesheet Content/Assets/Textures/jellyFish.spritesheet </summary>
                public struct jellyFish_spritesheet_TextureName
                {
                    
                    public const string jelly_animation_00000 = "jelly animation_00000";
                    
                    public const string jelly_animation_00001 = "jelly animation_00001";
                    
                    public const string jelly_animation_00002 = "jelly animation_00002";
                    
                    public const string jelly_animation_00003 = "jelly animation_00003";
                    
                    public const string jelly_animation_00004 = "jelly animation_00004";
                    
                    public const string jelly_animation_00005 = "jelly animation_00005";
                    
                    public const string jelly_animation_00006 = "jelly animation_00006";
                    
                    public const string jelly_animation_00007 = "jelly animation_00007";
                    
                    public const string jelly_animation_00008 = "jelly animation_00008";
                    
                    public const string jelly_animation_00009 = "jelly animation_00009";
                    
                    public const string jelly_animation_00010 = "jelly animation_00010";
                    
                    public const string jelly_animation_00011 = "jelly animation_00011";
                    
                    public const string jelly_animation_00012 = "jelly animation_00012";
                    
                    public const string jelly_animation_00013 = "jelly animation_00013";
                    
                    public const string jelly_animation_00014 = "jelly animation_00014";
                    
                    public const string jelly_animation_00015 = "jelly animation_00015";
                    
                    public const string jelly_animation_00016 = "jelly animation_00016";
                    
                    public const string jelly_animation_00017 = "jelly animation_00017";
                    
                    public const string jelly_animation_00018 = "jelly animation_00018";
                    
                    public const string jelly_animation_00019 = "jelly animation_00019";
                    
                    public const string jelly_animation_00020 = "jelly animation_00020";
                    
                    public const string jelly_animation_00021 = "jelly animation_00021";
                    
                    public const string jelly_animation_00022 = "jelly animation_00022";
                    
                    public const string jelly_animation_00023 = "jelly animation_00023";
                    
                    public const string jelly_animation_00024 = "jelly animation_00024";
                    
                    public const string jelly_animation_00025 = "jelly animation_00025";
                    
                    public const string jelly_animation_00026 = "jelly animation_00026";
                    
                    public const string jelly_animation_00027 = "jelly animation_00027";
                    
                    public const string jelly_animation_00028 = "jelly animation_00028";
                    
                    public const string jelly_animation_00029 = "jelly animation_00029";
                    
                    public const string jelly_animation_00030 = "jelly animation_00030";
                    
                    public const string jelly_animation_00031 = "jelly animation_00031";
                    
                    public const string jelly_animation_00032 = "jelly animation_00032";
                    
                    public const string jelly_animation_00033 = "jelly animation_00033";
                    
                    public const string jelly_animation_00034 = "jelly animation_00034";
                    
                    public const string jelly_animation_00035 = "jelly animation_00035";
                    
                    public const string jelly_animation_00036 = "jelly animation_00036";
                    
                    public const string jelly_animation_00037 = "jelly animation_00037";
                    
                    public const string jelly_animation_00038 = "jelly animation_00038";
                    
                    public const string jelly_animation_00039 = "jelly animation_00039";
                }
                
                /// <summary> Texture names from spritesheet Content/Assets/Textures/jellyFishLittle.spritesheet </summary>
                public struct jellyFishLittle_spritesheet_TextureName
                {
                    
                    public const string little_jellyfish_00000 = "little jellyfish_00000";
                    
                    public const string little_jellyfish_00001 = "little jellyfish_00001";
                    
                    public const string little_jellyfish_00002 = "little jellyfish_00002";
                    
                    public const string little_jellyfish_00003 = "little jellyfish_00003";
                    
                    public const string little_jellyfish_00004 = "little jellyfish_00004";
                    
                    public const string little_jellyfish_00005 = "little jellyfish_00005";
                    
                    public const string little_jellyfish_00006 = "little jellyfish_00006";
                    
                    public const string little_jellyfish_00007 = "little jellyfish_00007";
                    
                    public const string little_jellyfish_00008 = "little jellyfish_00008";
                    
                    public const string little_jellyfish_00009 = "little jellyfish_00009";
                    
                    public const string little_jellyfish_00010 = "little jellyfish_00010";
                    
                    public const string little_jellyfish_00011 = "little jellyfish_00011";
                    
                    public const string little_jellyfish_00012 = "little jellyfish_00012";
                    
                    public const string little_jellyfish_00013 = "little jellyfish_00013";
                    
                    public const string little_jellyfish_00014 = "little jellyfish_00014";
                    
                    public const string little_jellyfish_00015 = "little jellyfish_00015";
                    
                    public const string little_jellyfish_00016 = "little jellyfish_00016";
                    
                    public const string little_jellyfish_00017 = "little jellyfish_00017";
                    
                    public const string little_jellyfish_00018 = "little jellyfish_00018";
                    
                    public const string little_jellyfish_00019 = "little jellyfish_00019";
                    
                    public const string little_jellyfish_00020 = "little jellyfish_00020";
                    
                    public const string little_jellyfish_00021 = "little jellyfish_00021";
                    
                    public const string little_jellyfish_00022 = "little jellyfish_00022";
                    
                    public const string little_jellyfish_00023 = "little jellyfish_00023";
                    
                    public const string little_jellyfish_00024 = "little jellyfish_00024";
                    
                    public const string little_jellyfish_00025 = "little jellyfish_00025";
                    
                    public const string little_jellyfish_00026 = "little jellyfish_00026";
                    
                    public const string little_jellyfish_00027 = "little jellyfish_00027";
                    
                    public const string little_jellyfish_00028 = "little jellyfish_00028";
                    
                    public const string little_jellyfish_00029 = "little jellyfish_00029";
                    
                    public const string little_jellyfish_00030 = "little jellyfish_00030";
                    
                    public const string little_jellyfish_00031 = "little jellyfish_00031";
                    
                    public const string little_jellyfish_00032 = "little jellyfish_00032";
                    
                    public const string little_jellyfish_00033 = "little jellyfish_00033";
                    
                    public const string little_jellyfish_00034 = "little jellyfish_00034";
                    
                    public const string little_jellyfish_00035 = "little jellyfish_00035";
                    
                    public const string little_jellyfish_00036 = "little jellyfish_00036";
                    
                    public const string little_jellyfish_00037 = "little jellyfish_00037";
                    
                    public const string little_jellyfish_00038 = "little jellyfish_00038";
                    
                    public const string little_jellyfish_00039 = "little jellyfish_00039";
                }
                
                /// <summary> Texture names from spritesheet Content/Assets/Textures/seaweeds.spritesheet </summary>
                public struct seaweeds_spritesheet_TextureName
                {
                    
                    public const string final_seaweeds_00000 = "final seaweeds_00000";
                    
                    public const string final_seaweeds_00001 = "final seaweeds_00001";
                    
                    public const string final_seaweeds_00002 = "final seaweeds_00002";
                    
                    public const string final_seaweeds_00003 = "final seaweeds_00003";
                    
                    public const string final_seaweeds_00004 = "final seaweeds_00004";
                    
                    public const string final_seaweeds_00005 = "final seaweeds_00005";
                    
                    public const string final_seaweeds_00006 = "final seaweeds_00006";
                    
                    public const string final_seaweeds_00007 = "final seaweeds_00007";
                    
                    public const string final_seaweeds_00008 = "final seaweeds_00008";
                    
                    public const string final_seaweeds_00009 = "final seaweeds_00009";
                    
                    public const string final_seaweeds_00010 = "final seaweeds_00010";
                    
                    public const string final_seaweeds_00011 = "final seaweeds_00011";
                    
                    public const string final_seaweeds_00012 = "final seaweeds_00012";
                    
                    public const string final_seaweeds_00013 = "final seaweeds_00013";
                    
                    public const string final_seaweeds_00014 = "final seaweeds_00014";
                    
                    public const string final_seaweeds_00015 = "final seaweeds_00015";
                    
                    public const string final_seaweeds_00016 = "final seaweeds_00016";
                    
                    public const string final_seaweeds_00017 = "final seaweeds_00017";
                    
                    public const string final_seaweeds_00018 = "final seaweeds_00018";
                    
                    public const string final_seaweeds_00019 = "final seaweeds_00019";
                    
                    public const string final_seaweeds_00020 = "final seaweeds_00020";
                    
                    public const string final_seaweeds_00021 = "final seaweeds_00021";
                    
                    public const string final_seaweeds_00022 = "final seaweeds_00022";
                    
                    public const string final_seaweeds_00023 = "final seaweeds_00023";
                    
                    public const string final_seaweeds_00024 = "final seaweeds_00024";
                    
                    public const string final_seaweeds_00025 = "final seaweeds_00025";
                    
                    public const string final_seaweeds_00026 = "final seaweeds_00026";
                    
                    public const string final_seaweeds_00027 = "final seaweeds_00027";
                    
                    public const string final_seaweeds_00028 = "final seaweeds_00028";
                    
                    public const string final_seaweeds_00029 = "final seaweeds_00029";
                    
                    public const string final_seaweeds_00030 = "final seaweeds_00030";
                    
                    public const string final_seaweeds_00031 = "final seaweeds_00031";
                    
                    public const string final_seaweeds_00032 = "final seaweeds_00032";
                    
                    public const string final_seaweeds_00033 = "final seaweeds_00033";
                    
                    public const string final_seaweeds_00034 = "final seaweeds_00034";
                    
                    public const string final_seaweeds_00035 = "final seaweeds_00035";
                    
                    public const string final_seaweeds_00036 = "final seaweeds_00036";
                    
                    public const string final_seaweeds_00037 = "final seaweeds_00037";
                    
                    public const string final_seaweeds_00038 = "final seaweeds_00038";
                    
                    public const string final_seaweeds_00039 = "final seaweeds_00039";
                    
                    public const string final_seaweeds_00040 = "final seaweeds_00040";
                    
                    public const string final_seaweeds_00041 = "final seaweeds_00041";
                    
                    public const string final_seaweeds_00042 = "final seaweeds_00042";
                    
                    public const string final_seaweeds_00043 = "final seaweeds_00043";
                }
                
                /// <summary> Texture names from spritesheet Content/Assets/Textures/squiddd.spritesheet </summary>
                public struct squiddd_spritesheet_TextureName
                {
                    
                    public const string squid__00000 = "squid__00000";
                    
                    public const string squid__00001 = "squid__00001";
                    
                    public const string squid__00002 = "squid__00002";
                    
                    public const string squid__00003 = "squid__00003";
                    
                    public const string squid__00004 = "squid__00004";
                    
                    public const string squid__00005 = "squid__00005";
                    
                    public const string squid__00006 = "squid__00006";
                    
                    public const string squid__00007 = "squid__00007";
                    
                    public const string squid__00008 = "squid__00008";
                    
                    public const string squid__00009 = "squid__00009";
                    
                    public const string squid__00010 = "squid__00010";
                    
                    public const string squid__00011 = "squid__00011";
                    
                    public const string squid__00012 = "squid__00012";
                    
                    public const string squid__00013 = "squid__00013";
                    
                    public const string squid__00014 = "squid__00014";
                    
                    public const string squid__00015 = "squid__00015";
                    
                    public const string squid__00016 = "squid__00016";
                    
                    public const string squid__00017 = "squid__00017";
                    
                    public const string squid__00018 = "squid__00018";
                    
                    public const string squid__00019 = "squid__00019";
                    
                    public const string squid__00020 = "squid__00020";
                    
                    public const string squid__00021 = "squid__00021";
                    
                    public const string squid__00022 = "squid__00022";
                    
                    public const string squid__00023 = "squid__00023";
                    
                    public const string squid__00024 = "squid__00024";
                    
                    public const string squid__00025 = "squid__00025";
                    
                    public const string squid__00026 = "squid__00026";
                    
                    public const string squid__00027 = "squid__00027";
                    
                    public const string squid__00028 = "squid__00028";
                    
                    public const string squid__00029 = "squid__00029";
                }
            }
            
            public sealed class Materials
            {
                
                /// <summary> Path to Content/Assets/Materials/WaterParticleMaterial.wmat </summary>
                public const string WaterParticleMaterial = "Content/Assets/Materials/WaterParticleMaterial.wmat";
                
                /// <summary> Path to Content/Assets/Materials/WaterParticleMaterial2.wmat </summary>
                public const string WaterParticleMaterial2 = "Content/Assets/Materials/WaterParticleMaterial2.wmat";
            }
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/BackgroundScene.wscene </summary>
            public const string BackgroundScene = "Content/Scenes/BackgroundScene.wscene";
            
            /// <summary> Path to Content/Scenes/GameOverScene.wscene </summary>
            public const string GameOverScene = "Content/Scenes/GameOverScene.wscene";
            
            /// <summary> Path to Content/Scenes/GamePlayScene.wscene </summary>
            public const string GamePlayScene = "Content/Scenes/GamePlayScene.wscene";
            
            /// <summary> Path to Content/Scenes/MainMenuScene.wscene </summary>
            public const string MainMenuScene = "Content/Scenes/MainMenuScene.wscene";
        }
    }
}
