//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 02/05/2017 15:35:27
namespace MultiplayerTopDownTank
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        /// <summary> Path to Content/MultiplayerTopDownTank.wgame </summary>
        public const string GameInfo = "Content/MultiplayerTopDownTank.wgame";
        
        public sealed class Assets
        {
            
            public sealed class Fonts
            {
                
                /// <summary> Path to Content/Assets/Fonts/Top Secret.ttf </summary>
                public const string Top_Secret_ttf = "Content/Assets/Fonts/Top Secret.ttf";
            }
            
            public sealed class Gui
            {
                
                public sealed class Buttons
                {
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_BLK_TYPE_STATE (28).png </summary>
                    public const string BTN_BLK_TYPE_STATE_28_png = "Content/Assets/Gui/Buttons/BTN_BLK_TYPE_STATE (28).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_BLUE_CIRCLE_IN.png </summary>
                    public const string BTN_BLUE_CIRCLE_IN_png = "Content/Assets/Gui/Buttons/BTN_BLUE_CIRCLE_IN.png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_BLUE_CIRCLE_OUT.png </summary>
                    public const string BTN_BLUE_CIRCLE_OUT_png = "Content/Assets/Gui/Buttons/BTN_BLUE_CIRCLE_OUT.png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_BLUE_RECT_IN.png </summary>
                    public const string BTN_BLUE_RECT_IN_png = "Content/Assets/Gui/Buttons/BTN_BLUE_RECT_IN.png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_BLUE_RECT_OUT.png </summary>
                    public const string BTN_BLUE_RECT_OUT_png = "Content/Assets/Gui/Buttons/BTN_BLUE_RECT_OUT.png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_BLUE_SQ.png </summary>
                    public const string BTN_BLUE_SQ_png = "Content/Assets/Gui/Buttons/BTN_BLUE_SQ.png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_CHECKBOX_IN.png </summary>
                    public const string BTN_CHECKBOX_IN_png = "Content/Assets/Gui/Buttons/BTN_CHECKBOX_IN.png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_CHECKBOX_OUT.png </summary>
                    public const string BTN_CHECKBOX_OUT_png = "Content/Assets/Gui/Buttons/BTN_CHECKBOX_OUT.png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_GRAY_CIRCLE_IN.png </summary>
                    public const string BTN_GRAY_CIRCLE_IN_png = "Content/Assets/Gui/Buttons/BTN_GRAY_CIRCLE_IN.png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_GRAY_CIRCLE_OUT.png </summary>
                    public const string BTN_GRAY_CIRCLE_OUT_png = "Content/Assets/Gui/Buttons/BTN_GRAY_CIRCLE_OUT.png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_GRAY_RECT_IN.png </summary>
                    public const string BTN_GRAY_RECT_IN_png = "Content/Assets/Gui/Buttons/BTN_GRAY_RECT_IN.png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_GRAY_RECT_OUT.png </summary>
                    public const string BTN_GRAY_RECT_OUT_png = "Content/Assets/Gui/Buttons/BTN_GRAY_RECT_OUT.png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_GRAY_SQ.png </summary>
                    public const string BTN_GRAY_SQ_png = "Content/Assets/Gui/Buttons/BTN_GRAY_SQ.png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_GREEN_CIRCLE_IN.png </summary>
                    public const string BTN_GREEN_CIRCLE_IN_png = "Content/Assets/Gui/Buttons/BTN_GREEN_CIRCLE_IN.png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_GREEN_CIRCLE_OUT.png </summary>
                    public const string BTN_GREEN_CIRCLE_OUT_png = "Content/Assets/Gui/Buttons/BTN_GREEN_CIRCLE_OUT.png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_GREEN_RECT_IN.png </summary>
                    public const string BTN_GREEN_RECT_IN_png = "Content/Assets/Gui/Buttons/BTN_GREEN_RECT_IN.png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_GREEN_RECT_OUT.png </summary>
                    public const string BTN_GREEN_RECT_OUT_png = "Content/Assets/Gui/Buttons/BTN_GREEN_RECT_OUT.png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_GREEN_SQ.png </summary>
                    public const string BTN_GREEN_SQ_png = "Content/Assets/Gui/Buttons/BTN_GREEN_SQ.png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_HORIZ_SINGLE (1).png </summary>
                    public const string BTN_HORIZ_SINGLE_1_png = "Content/Assets/Gui/Buttons/BTN_HORIZ_SINGLE (1).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_HORIZ_SINGLE (10).png </summary>
                    public const string BTN_HORIZ_SINGLE_10_png = "Content/Assets/Gui/Buttons/BTN_HORIZ_SINGLE (10).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_HORIZ_SINGLE (11).png </summary>
                    public const string BTN_HORIZ_SINGLE_11_png = "Content/Assets/Gui/Buttons/BTN_HORIZ_SINGLE (11).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_HORIZ_SINGLE (12).png </summary>
                    public const string BTN_HORIZ_SINGLE_12_png = "Content/Assets/Gui/Buttons/BTN_HORIZ_SINGLE (12).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_HORIZ_SINGLE (13).png </summary>
                    public const string BTN_HORIZ_SINGLE_13_png = "Content/Assets/Gui/Buttons/BTN_HORIZ_SINGLE (13).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_HORIZ_SINGLE (14).png </summary>
                    public const string BTN_HORIZ_SINGLE_14_png = "Content/Assets/Gui/Buttons/BTN_HORIZ_SINGLE (14).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_HORIZ_SINGLE (15).png </summary>
                    public const string BTN_HORIZ_SINGLE_15_png = "Content/Assets/Gui/Buttons/BTN_HORIZ_SINGLE (15).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_HORIZ_SINGLE (16).png </summary>
                    public const string BTN_HORIZ_SINGLE_16_png = "Content/Assets/Gui/Buttons/BTN_HORIZ_SINGLE (16).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_HORIZ_SINGLE (17).png </summary>
                    public const string BTN_HORIZ_SINGLE_17_png = "Content/Assets/Gui/Buttons/BTN_HORIZ_SINGLE (17).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_HORIZ_SINGLE (18).png </summary>
                    public const string BTN_HORIZ_SINGLE_18_png = "Content/Assets/Gui/Buttons/BTN_HORIZ_SINGLE (18).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_HORIZ_SINGLE (19).png </summary>
                    public const string BTN_HORIZ_SINGLE_19_png = "Content/Assets/Gui/Buttons/BTN_HORIZ_SINGLE (19).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_HORIZ_SINGLE (2).png </summary>
                    public const string BTN_HORIZ_SINGLE_2_png = "Content/Assets/Gui/Buttons/BTN_HORIZ_SINGLE (2).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_HORIZ_SINGLE (20).png </summary>
                    public const string BTN_HORIZ_SINGLE_20_png = "Content/Assets/Gui/Buttons/BTN_HORIZ_SINGLE (20).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_HORIZ_SINGLE (21).png </summary>
                    public const string BTN_HORIZ_SINGLE_21_png = "Content/Assets/Gui/Buttons/BTN_HORIZ_SINGLE (21).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_HORIZ_SINGLE (22).png </summary>
                    public const string BTN_HORIZ_SINGLE_22_png = "Content/Assets/Gui/Buttons/BTN_HORIZ_SINGLE (22).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_HORIZ_SINGLE (23).png </summary>
                    public const string BTN_HORIZ_SINGLE_23_png = "Content/Assets/Gui/Buttons/BTN_HORIZ_SINGLE (23).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_HORIZ_SINGLE (24).png </summary>
                    public const string BTN_HORIZ_SINGLE_24_png = "Content/Assets/Gui/Buttons/BTN_HORIZ_SINGLE (24).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_HORIZ_SINGLE (3).png </summary>
                    public const string BTN_HORIZ_SINGLE_3_png = "Content/Assets/Gui/Buttons/BTN_HORIZ_SINGLE (3).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_HORIZ_SINGLE (4).png </summary>
                    public const string BTN_HORIZ_SINGLE_4_png = "Content/Assets/Gui/Buttons/BTN_HORIZ_SINGLE (4).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_HORIZ_SINGLE (5).png </summary>
                    public const string BTN_HORIZ_SINGLE_5_png = "Content/Assets/Gui/Buttons/BTN_HORIZ_SINGLE (5).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_HORIZ_SINGLE (6).png </summary>
                    public const string BTN_HORIZ_SINGLE_6_png = "Content/Assets/Gui/Buttons/BTN_HORIZ_SINGLE (6).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_HORIZ_SINGLE (7).png </summary>
                    public const string BTN_HORIZ_SINGLE_7_png = "Content/Assets/Gui/Buttons/BTN_HORIZ_SINGLE (7).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_HORIZ_SINGLE (8).png </summary>
                    public const string BTN_HORIZ_SINGLE_8_png = "Content/Assets/Gui/Buttons/BTN_HORIZ_SINGLE (8).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_HORIZ_SINGLE (9).png </summary>
                    public const string BTN_HORIZ_SINGLE_9_png = "Content/Assets/Gui/Buttons/BTN_HORIZ_SINGLE (9).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_LORANGE_CIRCLE_IN.png </summary>
                    public const string BTN_LORANGE_CIRCLE_IN_png = "Content/Assets/Gui/Buttons/BTN_LORANGE_CIRCLE_IN.png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_LORANGE_CIRCLE_OUT.png </summary>
                    public const string BTN_LORANGE_CIRCLE_OUT_png = "Content/Assets/Gui/Buttons/BTN_LORANGE_CIRCLE_OUT.png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_LORANGE_RECT_IN.png </summary>
                    public const string BTN_LORANGE_RECT_IN_png = "Content/Assets/Gui/Buttons/BTN_LORANGE_RECT_IN.png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_LORANGE_RECT_OUT.png </summary>
                    public const string BTN_LORANGE_RECT_OUT_png = "Content/Assets/Gui/Buttons/BTN_LORANGE_RECT_OUT.png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_ORANGE_CIRCLE_IN.png </summary>
                    public const string BTN_ORANGE_CIRCLE_IN_png = "Content/Assets/Gui/Buttons/BTN_ORANGE_CIRCLE_IN.png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_ORANGE_CIRCLE_OUT.png </summary>
                    public const string BTN_ORANGE_CIRCLE_OUT_png = "Content/Assets/Gui/Buttons/BTN_ORANGE_CIRCLE_OUT.png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_ORANGE_RECT_IN.png </summary>
                    public const string BTN_ORANGE_RECT_IN_png = "Content/Assets/Gui/Buttons/BTN_ORANGE_RECT_IN.png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_ORANGE_RECT_OUT.png </summary>
                    public const string BTN_ORANGE_RECT_OUT_png = "Content/Assets/Gui/Buttons/BTN_ORANGE_RECT_OUT.png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_ORANGE_SQ.png </summary>
                    public const string BTN_ORANGE_SQ_png = "Content/Assets/Gui/Buttons/BTN_ORANGE_SQ.png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_PLAIN (1).png </summary>
                    public const string BTN_PLAIN_1_png = "Content/Assets/Gui/Buttons/BTN_PLAIN (1).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_PLAIN (2).png </summary>
                    public const string BTN_PLAIN_2_png = "Content/Assets/Gui/Buttons/BTN_PLAIN (2).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_PLAIN (3).png </summary>
                    public const string BTN_PLAIN_3_png = "Content/Assets/Gui/Buttons/BTN_PLAIN (3).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_PLAIN (4).png </summary>
                    public const string BTN_PLAIN_4_png = "Content/Assets/Gui/Buttons/BTN_PLAIN (4).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_PLAIN (5).png </summary>
                    public const string BTN_PLAIN_5_png = "Content/Assets/Gui/Buttons/BTN_PLAIN (5).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_PLAIN (6).png </summary>
                    public const string BTN_PLAIN_6_png = "Content/Assets/Gui/Buttons/BTN_PLAIN (6).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_RADIO_IN.png </summary>
                    public const string BTN_RADIO_IN_png = "Content/Assets/Gui/Buttons/BTN_RADIO_IN.png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_RADIO_OUT.png </summary>
                    public const string BTN_RADIO_OUT_png = "Content/Assets/Gui/Buttons/BTN_RADIO_OUT.png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_RED_CIRCLE_IN.png </summary>
                    public const string BTN_RED_CIRCLE_IN_png = "Content/Assets/Gui/Buttons/BTN_RED_CIRCLE_IN.png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_RED_CIRCLE_OUT.png </summary>
                    public const string BTN_RED_CIRCLE_OUT_png = "Content/Assets/Gui/Buttons/BTN_RED_CIRCLE_OUT.png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_RED_RECT_IN.png </summary>
                    public const string BTN_RED_RECT_IN_png = "Content/Assets/Gui/Buttons/BTN_RED_RECT_IN.png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_RED_RECT_OUT.png </summary>
                    public const string BTN_RED_RECT_OUT_png = "Content/Assets/Gui/Buttons/BTN_RED_RECT_OUT.png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_RED_SQ.png </summary>
                    public const string BTN_RED_SQ_png = "Content/Assets/Gui/Buttons/BTN_RED_SQ.png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_SLIDER (1).png </summary>
                    public const string BTN_SLIDER_1_png = "Content/Assets/Gui/Buttons/BTN_SLIDER (1).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_SLIDER (10).png </summary>
                    public const string BTN_SLIDER_10_png = "Content/Assets/Gui/Buttons/BTN_SLIDER (10).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_SLIDER (11).png </summary>
                    public const string BTN_SLIDER_11_png = "Content/Assets/Gui/Buttons/BTN_SLIDER (11).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_SLIDER (12).png </summary>
                    public const string BTN_SLIDER_12_png = "Content/Assets/Gui/Buttons/BTN_SLIDER (12).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_SLIDER (2).png </summary>
                    public const string BTN_SLIDER_2_png = "Content/Assets/Gui/Buttons/BTN_SLIDER (2).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_SLIDER (3).png </summary>
                    public const string BTN_SLIDER_3_png = "Content/Assets/Gui/Buttons/BTN_SLIDER (3).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_SLIDER (4).png </summary>
                    public const string BTN_SLIDER_4_png = "Content/Assets/Gui/Buttons/BTN_SLIDER (4).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_SLIDER (5).png </summary>
                    public const string BTN_SLIDER_5_png = "Content/Assets/Gui/Buttons/BTN_SLIDER (5).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_SLIDER (6).png </summary>
                    public const string BTN_SLIDER_6_png = "Content/Assets/Gui/Buttons/BTN_SLIDER (6).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_SLIDER (7).png </summary>
                    public const string BTN_SLIDER_7_png = "Content/Assets/Gui/Buttons/BTN_SLIDER (7).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_SLIDER (8).png </summary>
                    public const string BTN_SLIDER_8_png = "Content/Assets/Gui/Buttons/BTN_SLIDER (8).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_SLIDER (9).png </summary>
                    public const string BTN_SLIDER_9_png = "Content/Assets/Gui/Buttons/BTN_SLIDER (9).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_SLIDER_SM (1).png </summary>
                    public const string BTN_SLIDER_SM_1_png = "Content/Assets/Gui/Buttons/BTN_SLIDER_SM (1).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_SLIDER_SM (10).png </summary>
                    public const string BTN_SLIDER_SM_10_png = "Content/Assets/Gui/Buttons/BTN_SLIDER_SM (10).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_SLIDER_SM (11).png </summary>
                    public const string BTN_SLIDER_SM_11_png = "Content/Assets/Gui/Buttons/BTN_SLIDER_SM (11).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_SLIDER_SM (12).png </summary>
                    public const string BTN_SLIDER_SM_12_png = "Content/Assets/Gui/Buttons/BTN_SLIDER_SM (12).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_SLIDER_SM (2).png </summary>
                    public const string BTN_SLIDER_SM_2_png = "Content/Assets/Gui/Buttons/BTN_SLIDER_SM (2).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_SLIDER_SM (3).png </summary>
                    public const string BTN_SLIDER_SM_3_png = "Content/Assets/Gui/Buttons/BTN_SLIDER_SM (3).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_SLIDER_SM (4).png </summary>
                    public const string BTN_SLIDER_SM_4_png = "Content/Assets/Gui/Buttons/BTN_SLIDER_SM (4).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_SLIDER_SM (5).png </summary>
                    public const string BTN_SLIDER_SM_5_png = "Content/Assets/Gui/Buttons/BTN_SLIDER_SM (5).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_SLIDER_SM (6).png </summary>
                    public const string BTN_SLIDER_SM_6_png = "Content/Assets/Gui/Buttons/BTN_SLIDER_SM (6).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_SLIDER_SM (7).png </summary>
                    public const string BTN_SLIDER_SM_7_png = "Content/Assets/Gui/Buttons/BTN_SLIDER_SM (7).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_SLIDER_SM (8).png </summary>
                    public const string BTN_SLIDER_SM_8_png = "Content/Assets/Gui/Buttons/BTN_SLIDER_SM (8).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_SLIDER_SM (9).png </summary>
                    public const string BTN_SLIDER_SM_9_png = "Content/Assets/Gui/Buttons/BTN_SLIDER_SM (9).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_VERT_ (1).png </summary>
                    public const string BTN_VERT__1_png = "Content/Assets/Gui/Buttons/BTN_VERT_ (1).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_VERT_ (10).png </summary>
                    public const string BTN_VERT__10_png = "Content/Assets/Gui/Buttons/BTN_VERT_ (10).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_VERT_ (11).png </summary>
                    public const string BTN_VERT__11_png = "Content/Assets/Gui/Buttons/BTN_VERT_ (11).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_VERT_ (12).png </summary>
                    public const string BTN_VERT__12_png = "Content/Assets/Gui/Buttons/BTN_VERT_ (12).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_VERT_ (13).png </summary>
                    public const string BTN_VERT__13_png = "Content/Assets/Gui/Buttons/BTN_VERT_ (13).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_VERT_ (14).png </summary>
                    public const string BTN_VERT__14_png = "Content/Assets/Gui/Buttons/BTN_VERT_ (14).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_VERT_ (15).png </summary>
                    public const string BTN_VERT__15_png = "Content/Assets/Gui/Buttons/BTN_VERT_ (15).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_VERT_ (16).png </summary>
                    public const string BTN_VERT__16_png = "Content/Assets/Gui/Buttons/BTN_VERT_ (16).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_VERT_ (17).png </summary>
                    public const string BTN_VERT__17_png = "Content/Assets/Gui/Buttons/BTN_VERT_ (17).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_VERT_ (18).png </summary>
                    public const string BTN_VERT__18_png = "Content/Assets/Gui/Buttons/BTN_VERT_ (18).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_VERT_ (19).png </summary>
                    public const string BTN_VERT__19_png = "Content/Assets/Gui/Buttons/BTN_VERT_ (19).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_VERT_ (2).png </summary>
                    public const string BTN_VERT__2_png = "Content/Assets/Gui/Buttons/BTN_VERT_ (2).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_VERT_ (20).png </summary>
                    public const string BTN_VERT__20_png = "Content/Assets/Gui/Buttons/BTN_VERT_ (20).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_VERT_ (21).png </summary>
                    public const string BTN_VERT__21_png = "Content/Assets/Gui/Buttons/BTN_VERT_ (21).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_VERT_ (22).png </summary>
                    public const string BTN_VERT__22_png = "Content/Assets/Gui/Buttons/BTN_VERT_ (22).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_VERT_ (23).png </summary>
                    public const string BTN_VERT__23_png = "Content/Assets/Gui/Buttons/BTN_VERT_ (23).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_VERT_ (24).png </summary>
                    public const string BTN_VERT__24_png = "Content/Assets/Gui/Buttons/BTN_VERT_ (24).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_VERT_ (25).png </summary>
                    public const string BTN_VERT__25_png = "Content/Assets/Gui/Buttons/BTN_VERT_ (25).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_VERT_ (26).png </summary>
                    public const string BTN_VERT__26_png = "Content/Assets/Gui/Buttons/BTN_VERT_ (26).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_VERT_ (27).png </summary>
                    public const string BTN_VERT__27_png = "Content/Assets/Gui/Buttons/BTN_VERT_ (27).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_VERT_ (28).png </summary>
                    public const string BTN_VERT__28_png = "Content/Assets/Gui/Buttons/BTN_VERT_ (28).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_VERT_ (29).png </summary>
                    public const string BTN_VERT__29_png = "Content/Assets/Gui/Buttons/BTN_VERT_ (29).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_VERT_ (3).png </summary>
                    public const string BTN_VERT__3_png = "Content/Assets/Gui/Buttons/BTN_VERT_ (3).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_VERT_ (30).png </summary>
                    public const string BTN_VERT__30_png = "Content/Assets/Gui/Buttons/BTN_VERT_ (30).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_VERT_ (4).png </summary>
                    public const string BTN_VERT__4_png = "Content/Assets/Gui/Buttons/BTN_VERT_ (4).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_VERT_ (5).png </summary>
                    public const string BTN_VERT__5_png = "Content/Assets/Gui/Buttons/BTN_VERT_ (5).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_VERT_ (6).png </summary>
                    public const string BTN_VERT__6_png = "Content/Assets/Gui/Buttons/BTN_VERT_ (6).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_VERT_ (7).png </summary>
                    public const string BTN_VERT__7_png = "Content/Assets/Gui/Buttons/BTN_VERT_ (7).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_VERT_ (8).png </summary>
                    public const string BTN_VERT__8_png = "Content/Assets/Gui/Buttons/BTN_VERT_ (8).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/BTN_VERT_ (9).png </summary>
                    public const string BTN_VERT__9_png = "Content/Assets/Gui/Buttons/BTN_VERT_ (9).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/flatDark00.png </summary>
                    public const string flatDark00_png = "Content/Assets/Gui/Buttons/flatDark00.png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/flatDark06.png </summary>
                    public const string flatDark06_png = "Content/Assets/Gui/Buttons/flatDark06.png";
                    
                    /// <summary> Path to Content/Assets/Gui/Buttons/flatDark48.png </summary>
                    public const string flatDark48_png = "Content/Assets/Gui/Buttons/flatDark48.png";
                }
                
                public sealed class Menu
                {
                    
                    /// <summary> Path to Content/Assets/Gui/Menu/UI_WINDOW (1).png </summary>
                    public const string UI_WINDOW_1_png = "Content/Assets/Gui/Menu/UI_WINDOW (1).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Menu/UI_WINDOW (2).png </summary>
                    public const string UI_WINDOW_2_png = "Content/Assets/Gui/Menu/UI_WINDOW (2).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Menu/UI_WINDOW (3).png </summary>
                    public const string UI_WINDOW_3_png = "Content/Assets/Gui/Menu/UI_WINDOW (3).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Menu/UI_WINDOW (4).png </summary>
                    public const string UI_WINDOW_4_png = "Content/Assets/Gui/Menu/UI_WINDOW (4).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Menu/UI_WINDOW (5).png </summary>
                    public const string UI_WINDOW_5_png = "Content/Assets/Gui/Menu/UI_WINDOW (5).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Menu/UI_WINDOW (6).png </summary>
                    public const string UI_WINDOW_6_png = "Content/Assets/Gui/Menu/UI_WINDOW (6).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Menu/UI_WINDOW (7).png </summary>
                    public const string UI_WINDOW_7_png = "Content/Assets/Gui/Menu/UI_WINDOW (7).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Menu/UI_WINDOW (8).png </summary>
                    public const string UI_WINDOW_8_png = "Content/Assets/Gui/Menu/UI_WINDOW (8).png";
                    
                    /// <summary> Path to Content/Assets/Gui/Menu/UI_WINDOW (9).png </summary>
                    public const string UI_WINDOW_9_png = "Content/Assets/Gui/Menu/UI_WINDOW (9).png";
                }
            }
            
            public sealed class Sounds
            {
                
                /// <summary> Path to Content/Assets/Sounds/Background Music.mp3 </summary>
                public const string Background_Music_mp3 = "Content/Assets/Sounds/Background Music.mp3";
                
                /// <summary> Path to Content/Assets/Sounds/Tank Firing Sound.wav </summary>
                public const string Tank_Firing_Sound_wav = "Content/Assets/Sounds/Tank Firing Sound.wav";
                
                /// <summary> Path to Content/Assets/Sounds/Tank Sound.wav </summary>
                public const string Tank_Sound_wav = "Content/Assets/Sounds/Tank Sound.wav";
            }
            
            public sealed class Textures
            {
                
                public sealed class Adorners
                {
                    
                    /// <summary> Path to Content/Assets/Textures/Adorners/adorner01.png </summary>
                    public const string adorner01_png = "Content/Assets/Textures/Adorners/adorner01.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Adorners/adorner02.png </summary>
                    public const string adorner02_png = "Content/Assets/Textures/Adorners/adorner02.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Adorners/adorner03.png </summary>
                    public const string adorner03_png = "Content/Assets/Textures/Adorners/adorner03.png";
                }
                
                public sealed class Bullets
                {
                    
                    /// <summary> Path to Content/Assets/Textures/Bullets/bulletBeige.png </summary>
                    public const string bulletBeige_png = "Content/Assets/Textures/Bullets/bulletBeige.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Bullets/bulletBeigeSilver.png </summary>
                    public const string bulletBeigeSilver_png = "Content/Assets/Textures/Bullets/bulletBeigeSilver.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Bullets/bulletBeigeSilver_outline.png </summary>
                    public const string bulletBeigeSilver_outline_png = "Content/Assets/Textures/Bullets/bulletBeigeSilver_outline.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Bullets/bulletBeige_outline.png </summary>
                    public const string bulletBeige_outline_png = "Content/Assets/Textures/Bullets/bulletBeige_outline.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Bullets/bulletBlue.png </summary>
                    public const string bulletBlue_png = "Content/Assets/Textures/Bullets/bulletBlue.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Bullets/bulletBlueSilver.png </summary>
                    public const string bulletBlueSilver_png = "Content/Assets/Textures/Bullets/bulletBlueSilver.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Bullets/bulletBlueSilver_outline.png </summary>
                    public const string bulletBlueSilver_outline_png = "Content/Assets/Textures/Bullets/bulletBlueSilver_outline.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Bullets/bulletBlue_outline.png </summary>
                    public const string bulletBlue_outline_png = "Content/Assets/Textures/Bullets/bulletBlue_outline.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Bullets/bulletGreen.png </summary>
                    public const string bulletGreen_png = "Content/Assets/Textures/Bullets/bulletGreen.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Bullets/bulletGreenSilver.png </summary>
                    public const string bulletGreenSilver_png = "Content/Assets/Textures/Bullets/bulletGreenSilver.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Bullets/bulletGreenSilver_outline.png </summary>
                    public const string bulletGreenSilver_outline_png = "Content/Assets/Textures/Bullets/bulletGreenSilver_outline.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Bullets/bulletGreen_outline.png </summary>
                    public const string bulletGreen_outline_png = "Content/Assets/Textures/Bullets/bulletGreen_outline.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Bullets/bulletRed.png </summary>
                    public const string bulletRed_png = "Content/Assets/Textures/Bullets/bulletRed.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Bullets/bulletRedSilver.png </summary>
                    public const string bulletRedSilver_png = "Content/Assets/Textures/Bullets/bulletRedSilver.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Bullets/bulletRedSilver_outline.png </summary>
                    public const string bulletRedSilver_outline_png = "Content/Assets/Textures/Bullets/bulletRedSilver_outline.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Bullets/bulletRed_outline.png </summary>
                    public const string bulletRed_outline_png = "Content/Assets/Textures/Bullets/bulletRed_outline.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Bullets/bulletSilver.png </summary>
                    public const string bulletSilver_png = "Content/Assets/Textures/Bullets/bulletSilver.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Bullets/bulletSilverSilver.png </summary>
                    public const string bulletSilverSilver_png = "Content/Assets/Textures/Bullets/bulletSilverSilver.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Bullets/bulletSilverSilver_outline.png </summary>
                    public const string bulletSilverSilver_outline_png = "Content/Assets/Textures/Bullets/bulletSilverSilver_outline.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Bullets/bulletSilver_outline.png </summary>
                    public const string bulletSilver_outline_png = "Content/Assets/Textures/Bullets/bulletSilver_outline.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Bullets/bulletYellow.png </summary>
                    public const string bulletYellow_png = "Content/Assets/Textures/Bullets/bulletYellow.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Bullets/bulletYellowSilver.png </summary>
                    public const string bulletYellowSilver_png = "Content/Assets/Textures/Bullets/bulletYellowSilver.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Bullets/bulletYellowSilver_outline.png </summary>
                    public const string bulletYellowSilver_outline_png = "Content/Assets/Textures/Bullets/bulletYellowSilver_outline.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Bullets/bulletYellow_outline.png </summary>
                    public const string bulletYellow_outline_png = "Content/Assets/Textures/Bullets/bulletYellow_outline.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Bullets/rounded_bulletBeige_outline.png </summary>
                    public const string rounded_bulletBeige_outline_png = "Content/Assets/Textures/Bullets/rounded_bulletBeige_outline.png";
                }
                
                public sealed class Environment
                {
                    
                    /// <summary> Path to Content/Assets/Textures/Environment/dirt.png </summary>
                    public const string dirt_png = "Content/Assets/Textures/Environment/dirt.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Environment/grass.png </summary>
                    public const string grass_png = "Content/Assets/Textures/Environment/grass.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Environment/multipletrees.png </summary>
                    public const string multipletrees_png = "Content/Assets/Textures/Environment/multipletrees.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Environment/sand.png </summary>
                    public const string sand_png = "Content/Assets/Textures/Environment/sand.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Environment/semidirt.png </summary>
                    public const string semidirt_png = "Content/Assets/Textures/Environment/semidirt.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Environment/treeLarge.png </summary>
                    public const string treeLarge_png = "Content/Assets/Textures/Environment/treeLarge.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Environment/treeSmall.png </summary>
                    public const string treeSmall_png = "Content/Assets/Textures/Environment/treeSmall.png";
                }
                
                public sealed class Obstacles
                {
                    
                    /// <summary> Path to Content/Assets/Textures/Obstacles/barrelGreen_side.png </summary>
                    public const string barrelGreen_side_png = "Content/Assets/Textures/Obstacles/barrelGreen_side.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Obstacles/barrelGreen_side_damaged.png </summary>
                    public const string barrelGreen_side_damaged_png = "Content/Assets/Textures/Obstacles/barrelGreen_side_damaged.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Obstacles/barrelGreen_up.png </summary>
                    public const string barrelGreen_up_png = "Content/Assets/Textures/Obstacles/barrelGreen_up.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Obstacles/barrelGrey_sde_rust.png </summary>
                    public const string barrelGrey_sde_rust_png = "Content/Assets/Textures/Obstacles/barrelGrey_sde_rust.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Obstacles/barrelGrey_side.png </summary>
                    public const string barrelGrey_side_png = "Content/Assets/Textures/Obstacles/barrelGrey_side.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Obstacles/barrelGrey_up.png </summary>
                    public const string barrelGrey_up_png = "Content/Assets/Textures/Obstacles/barrelGrey_up.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Obstacles/barrelRed_side.png </summary>
                    public const string barrelRed_side_png = "Content/Assets/Textures/Obstacles/barrelRed_side.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Obstacles/barrelRed_up.png </summary>
                    public const string barrelRed_up_png = "Content/Assets/Textures/Obstacles/barrelRed_up.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Obstacles/bigSandbagBrown.png </summary>
                    public const string bigSandbagBrown_png = "Content/Assets/Textures/Obstacles/bigSandbagBrown.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Obstacles/oil.png </summary>
                    public const string oil_png = "Content/Assets/Textures/Obstacles/oil.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Obstacles/sandbagBeige.png </summary>
                    public const string sandbagBeige_png = "Content/Assets/Textures/Obstacles/sandbagBeige.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Obstacles/sandbagBrown.png </summary>
                    public const string sandbagBrown_png = "Content/Assets/Textures/Obstacles/sandbagBrown.png";
                }
                
                public sealed class Powerups
                {
                    
                    /// <summary> Path to Content/Assets/Textures/Powerups/tanks_crateAmmo.png </summary>
                    public const string tanks_crateAmmo_png = "Content/Assets/Textures/Powerups/tanks_crateAmmo.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Powerups/tanks_crateArmor.png </summary>
                    public const string tanks_crateArmor_png = "Content/Assets/Textures/Powerups/tanks_crateArmor.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Powerups/tanks_crateRepair.png </summary>
                    public const string tanks_crateRepair_png = "Content/Assets/Textures/Powerups/tanks_crateRepair.png";
                }
                
                public sealed class Smoke
                {
                    
                    /// <summary> Path to Content/Assets/Textures/Smoke/smokeGrey0.png </summary>
                    public const string smokeGrey0_png = "Content/Assets/Textures/Smoke/smokeGrey0.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Smoke/smokeGrey1.png </summary>
                    public const string smokeGrey1_png = "Content/Assets/Textures/Smoke/smokeGrey1.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Smoke/smokeGrey2.png </summary>
                    public const string smokeGrey2_png = "Content/Assets/Textures/Smoke/smokeGrey2.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Smoke/smokeGrey3.png </summary>
                    public const string smokeGrey3_png = "Content/Assets/Textures/Smoke/smokeGrey3.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Smoke/smokeGrey4.png </summary>
                    public const string smokeGrey4_png = "Content/Assets/Textures/Smoke/smokeGrey4.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Smoke/smokeGrey5.png </summary>
                    public const string smokeGrey5_png = "Content/Assets/Textures/Smoke/smokeGrey5.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Smoke/smokeOrange0.png </summary>
                    public const string smokeOrange0_png = "Content/Assets/Textures/Smoke/smokeOrange0.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Smoke/smokeOrange1.png </summary>
                    public const string smokeOrange1_png = "Content/Assets/Textures/Smoke/smokeOrange1.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Smoke/smokeOrange2.png </summary>
                    public const string smokeOrange2_png = "Content/Assets/Textures/Smoke/smokeOrange2.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Smoke/smokeOrange3.png </summary>
                    public const string smokeOrange3_png = "Content/Assets/Textures/Smoke/smokeOrange3.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Smoke/smokeOrange4.png </summary>
                    public const string smokeOrange4_png = "Content/Assets/Textures/Smoke/smokeOrange4.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Smoke/smokeOrange5.png </summary>
                    public const string smokeOrange5_png = "Content/Assets/Textures/Smoke/smokeOrange5.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Smoke/smokeWhite0.png </summary>
                    public const string smokeWhite0_png = "Content/Assets/Textures/Smoke/smokeWhite0.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Smoke/smokeWhite1.png </summary>
                    public const string smokeWhite1_png = "Content/Assets/Textures/Smoke/smokeWhite1.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Smoke/smokeWhite2.png </summary>
                    public const string smokeWhite2_png = "Content/Assets/Textures/Smoke/smokeWhite2.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Smoke/smokeWhite3.png </summary>
                    public const string smokeWhite3_png = "Content/Assets/Textures/Smoke/smokeWhite3.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Smoke/smokeWhite4.png </summary>
                    public const string smokeWhite4_png = "Content/Assets/Textures/Smoke/smokeWhite4.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Smoke/smokeWhite5.png </summary>
                    public const string smokeWhite5_png = "Content/Assets/Textures/Smoke/smokeWhite5.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Smoke/smokeYellow0.png </summary>
                    public const string smokeYellow0_png = "Content/Assets/Textures/Smoke/smokeYellow0.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Smoke/smokeYellow1.png </summary>
                    public const string smokeYellow1_png = "Content/Assets/Textures/Smoke/smokeYellow1.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Smoke/smokeYellow2.png </summary>
                    public const string smokeYellow2_png = "Content/Assets/Textures/Smoke/smokeYellow2.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Smoke/smokeYellow3.png </summary>
                    public const string smokeYellow3_png = "Content/Assets/Textures/Smoke/smokeYellow3.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Smoke/smokeYellow4.png </summary>
                    public const string smokeYellow4_png = "Content/Assets/Textures/Smoke/smokeYellow4.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Smoke/smokeYellow5.png </summary>
                    public const string smokeYellow5_png = "Content/Assets/Textures/Smoke/smokeYellow5.png";
                }
                
                public sealed class Tanks
                {
                    
                    /// <summary> Path to Content/Assets/Textures/Tanks/barrelBeige.png </summary>
                    public const string barrelBeige_png = "Content/Assets/Textures/Tanks/barrelBeige.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Tanks/barrelBeige_outline.png </summary>
                    public const string barrelBeige_outline_png = "Content/Assets/Textures/Tanks/barrelBeige_outline.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Tanks/barrelBlack.png </summary>
                    public const string barrelBlack_png = "Content/Assets/Textures/Tanks/barrelBlack.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Tanks/barrelBlack_outline.png </summary>
                    public const string barrelBlack_outline_png = "Content/Assets/Textures/Tanks/barrelBlack_outline.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Tanks/barrelBlue.png </summary>
                    public const string barrelBlue_png = "Content/Assets/Textures/Tanks/barrelBlue.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Tanks/barrelBlue_outline.png </summary>
                    public const string barrelBlue_outline_png = "Content/Assets/Textures/Tanks/barrelBlue_outline.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Tanks/barrelGreen.png </summary>
                    public const string barrelGreen_png = "Content/Assets/Textures/Tanks/barrelGreen.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Tanks/barrelGreen_outline.png </summary>
                    public const string barrelGreen_outline_png = "Content/Assets/Textures/Tanks/barrelGreen_outline.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Tanks/barrelRed.png </summary>
                    public const string barrelRed_png = "Content/Assets/Textures/Tanks/barrelRed.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Tanks/barrelRed_outline.png </summary>
                    public const string barrelRed_outline_png = "Content/Assets/Textures/Tanks/barrelRed_outline.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Tanks/tankBeige.png </summary>
                    public const string tankBeige_png = "Content/Assets/Textures/Tanks/tankBeige.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Tanks/tankBeige_outline.png </summary>
                    public const string tankBeige_outline_png = "Content/Assets/Textures/Tanks/tankBeige_outline.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Tanks/tankBlack.png </summary>
                    public const string tankBlack_png = "Content/Assets/Textures/Tanks/tankBlack.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Tanks/tankBlack_outline.png </summary>
                    public const string tankBlack_outline_png = "Content/Assets/Textures/Tanks/tankBlack_outline.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Tanks/tankBlue.png </summary>
                    public const string tankBlue_png = "Content/Assets/Textures/Tanks/tankBlue.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Tanks/tankBlue_outline.png </summary>
                    public const string tankBlue_outline_png = "Content/Assets/Textures/Tanks/tankBlue_outline.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Tanks/tankGreen.png </summary>
                    public const string tankGreen_png = "Content/Assets/Textures/Tanks/tankGreen.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Tanks/tankGreen_outline.png </summary>
                    public const string tankGreen_outline_png = "Content/Assets/Textures/Tanks/tankGreen_outline.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Tanks/tankRed.png </summary>
                    public const string tankRed_png = "Content/Assets/Textures/Tanks/tankRed.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Tanks/tankRed_outline.png </summary>
                    public const string tankRed_outline_png = "Content/Assets/Textures/Tanks/tankRed_outline.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Tanks/tanks_tankDesert1.png </summary>
                    public const string tanks_tankDesert1_png = "Content/Assets/Textures/Tanks/tanks_tankDesert1.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Tanks/tanks_tankDesert2.png </summary>
                    public const string tanks_tankDesert2_png = "Content/Assets/Textures/Tanks/tanks_tankDesert2.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Tanks/tanks_tankDesert3.png </summary>
                    public const string tanks_tankDesert3_png = "Content/Assets/Textures/Tanks/tanks_tankDesert3.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Tanks/tanks_tankDesert4.png </summary>
                    public const string tanks_tankDesert4_png = "Content/Assets/Textures/Tanks/tanks_tankDesert4.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Tanks/tanks_tankGreen1.png </summary>
                    public const string tanks_tankGreen1_png = "Content/Assets/Textures/Tanks/tanks_tankGreen1.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Tanks/tanks_tankGreen2.png </summary>
                    public const string tanks_tankGreen2_png = "Content/Assets/Textures/Tanks/tanks_tankGreen2.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Tanks/tanks_tankGreen3.png </summary>
                    public const string tanks_tankGreen3_png = "Content/Assets/Textures/Tanks/tanks_tankGreen3.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Tanks/tanks_tankGreen4.png </summary>
                    public const string tanks_tankGreen4_png = "Content/Assets/Textures/Tanks/tanks_tankGreen4.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Tanks/tanks_tankGrey1.png </summary>
                    public const string tanks_tankGrey1_png = "Content/Assets/Textures/Tanks/tanks_tankGrey1.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Tanks/tanks_tankGrey2.png </summary>
                    public const string tanks_tankGrey2_png = "Content/Assets/Textures/Tanks/tanks_tankGrey2.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Tanks/tanks_tankGrey3.png </summary>
                    public const string tanks_tankGrey3_png = "Content/Assets/Textures/Tanks/tanks_tankGrey3.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Tanks/tanks_tankGrey4.png </summary>
                    public const string tanks_tankGrey4_png = "Content/Assets/Textures/Tanks/tanks_tankGrey4.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Tanks/tanks_tankNavy1.png </summary>
                    public const string tanks_tankNavy1_png = "Content/Assets/Textures/Tanks/tanks_tankNavy1.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Tanks/tanks_tankNavy2.png </summary>
                    public const string tanks_tankNavy2_png = "Content/Assets/Textures/Tanks/tanks_tankNavy2.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Tanks/tanks_tankNavy3.png </summary>
                    public const string tanks_tankNavy3_png = "Content/Assets/Textures/Tanks/tanks_tankNavy3.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Tanks/tanks_tankNavy4.png </summary>
                    public const string tanks_tankNavy4_png = "Content/Assets/Textures/Tanks/tanks_tankNavy4.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Tanks/tracksLarge.png </summary>
                    public const string tracksLarge_png = "Content/Assets/Textures/Tanks/tracksLarge.png";
                    
                    /// <summary> Path to Content/Assets/Textures/Tanks/tracksSmall.png </summary>
                    public const string tracksSmall_png = "Content/Assets/Textures/Tanks/tracksSmall.png";
                }
            }
            
            public sealed class Tiles
            {
                
                /// <summary> Path to Content/Assets/Tiles/Map.tmx </summary>
                public const string Map_tmx = "Content/Assets/Tiles/Map.tmx";
                
                /// <summary> Path to Content/Assets/Tiles/MultiplayerTopDownTankSpritesheet.png </summary>
                public const string MultiplayerTopDownTankSpritesheet_png = "Content/Assets/Tiles/MultiplayerTopDownTankSpritesheet.png";
            }
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/GameScene.wscene </summary>
            public const string GameScene = "Content/Scenes/GameScene.wscene";
            
            /// <summary> Path to Content/Scenes/LobbyScene.wscene </summary>
            public const string LobbyScene = "Content/Scenes/LobbyScene.wscene";
            
            /// <summary> Path to Content/Scenes/MenuScene.wscene </summary>
            public const string MenuScene = "Content/Scenes/MenuScene.wscene";
            
            /// <summary> Path to Content/Scenes/ScoreScene.wscene </summary>
            public const string ScoreScene = "Content/Scenes/ScoreScene.wscene";
        }
    }
}
