//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 1/28/2016 5:06:34 PM
namespace BasketKing
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        public sealed class Assets
        {
            
            public sealed class Fonts
            {
                
                /// <summary> Path to Content/Assets/Fonts/Gotham Bold_16.ttf </summary>
                public const string Gotham_Bold_16_ttf = "Content/Assets/Fonts/Gotham Bold_16.ttf";
                
                /// <summary> Path to Content/Assets/Fonts/spritefont_time.ttf </summary>
                public const string spritefont_time_ttf = "Content/Assets/Fonts/spritefont_time.ttf";
            }
            
            public sealed class Sounds
            {
                
                /// <summary> Path to Content/Assets/Sounds/bg_ambient.mp3 </summary>
                public const string bg_ambient_mp3 = "Content/Assets/Sounds/bg_ambient.mp3";
                
                /// <summary> Path to Content/Assets/Sounds/bg_music.mp3 </summary>
                public const string bg_music_mp3 = "Content/Assets/Sounds/bg_music.mp3";
                
                /// <summary> Path to Content/Assets/Sounds/button.wav </summary>
                public const string button_wav = "Content/Assets/Sounds/button.wav";
                
                /// <summary> Path to Content/Assets/Sounds/digit.wav </summary>
                public const string digit_wav = "Content/Assets/Sounds/digit.wav";
                
                /// <summary> Path to Content/Assets/Sounds/go.wav </summary>
                public const string go_wav = "Content/Assets/Sounds/go.wav";
                
                /// <summary> Path to Content/Assets/Sounds/hoop.wav </summary>
                public const string hoop_wav = "Content/Assets/Sounds/hoop.wav";
                
                /// <summary> Path to Content/Assets/Sounds/hurryUp.wav </summary>
                public const string hurryUp_wav = "Content/Assets/Sounds/hurryUp.wav";
                
                /// <summary> Path to Content/Assets/Sounds/net.wav </summary>
                public const string net_wav = "Content/Assets/Sounds/net.wav";
                
                /// <summary> Path to Content/Assets/Sounds/ready.wav </summary>
                public const string ready_wav = "Content/Assets/Sounds/ready.wav";
                
                /// <summary> Path to Content/Assets/Sounds/record.wav </summary>
                public const string record_wav = "Content/Assets/Sounds/record.wav";
                
                /// <summary> Path to Content/Assets/Sounds/tablet.wav </summary>
                public const string tablet_wav = "Content/Assets/Sounds/tablet.wav";
                
                /// <summary> Path to Content/Assets/Sounds/timeOver.wav </summary>
                public const string timeOver_wav = "Content/Assets/Sounds/timeOver.wav";
                
                /// <summary> Path to Content/Assets/Sounds/yeah.wav </summary>
                public const string yeah_wav = "Content/Assets/Sounds/yeah.wav";
            }
            
            public sealed class Textures
            {
                
                /// <summary> Path to Content/Assets/Textures/ball.PNG </summary>
                public const string ball_PNG = "Content/Assets/Textures/ball.PNG";
                
                /// <summary> Path to Content/Assets/Textures/ball2.PNG </summary>
                public const string ball2_PNG = "Content/Assets/Textures/ball2.PNG";
                
                /// <summary> Path to Content/Assets/Textures/BallFire.spritesheet </summary>
                public const string BallFire_spritesheet = "Content/Assets/Textures/BallFire.spritesheet";
                
                /// <summary> Path to Content/Assets/Textures/ball_shines.PNG </summary>
                public const string ball_shines_PNG = "Content/Assets/Textures/ball_shines.PNG";
                
                /// <summary> Path to Content/Assets/Textures/ball_target.PNG </summary>
                public const string ball_target_PNG = "Content/Assets/Textures/ball_target.PNG";
                
                /// <summary> Path to Content/Assets/Textures/basket.PNG </summary>
                public const string basket_PNG = "Content/Assets/Textures/basket.PNG";
                
                /// <summary> Path to Content/Assets/Textures/basketTable.png </summary>
                public const string basketTable_png = "Content/Assets/Textures/basketTable.png";
                
                /// <summary> Path to Content/Assets/Textures/basket_piece_front.PNG </summary>
                public const string basket_piece_front_PNG = "Content/Assets/Textures/basket_piece_front.PNG";
                
                /// <summary> Path to Content/Assets/Textures/betheking.png </summary>
                public const string betheking_png = "Content/Assets/Textures/betheking.png";
                
                /// <summary> Path to Content/Assets/Textures/bg.PNG </summary>
                public const string bg_PNG = "Content/Assets/Textures/bg.PNG";
                
                /// <summary> Path to Content/Assets/Textures/bg_combo.PNG </summary>
                public const string bg_combo_PNG = "Content/Assets/Textures/bg_combo.PNG";
                
                /// <summary> Path to Content/Assets/Textures/bg_final_score.PNG </summary>
                public const string bg_final_score_PNG = "Content/Assets/Textures/bg_final_score.PNG";
                
                /// <summary> Path to Content/Assets/Textures/bg_highscore.PNG </summary>
                public const string bg_highscore_PNG = "Content/Assets/Textures/bg_highscore.PNG";
                
                /// <summary> Path to Content/Assets/Textures/bg_options_pause.PNG </summary>
                public const string bg_options_pause_PNG = "Content/Assets/Textures/bg_options_pause.PNG";
                
                /// <summary> Path to Content/Assets/Textures/bg_panel.PNG </summary>
                public const string bg_panel_PNG = "Content/Assets/Textures/bg_panel.PNG";
                
                /// <summary> Path to Content/Assets/Textures/BK_logo.PNG </summary>
                public const string BK_logo_PNG = "Content/Assets/Textures/BK_logo.PNG";
                
                /// <summary> Path to Content/Assets/Textures/dummyPin.png </summary>
                public const string dummyPin_png = "Content/Assets/Textures/dummyPin.png";
                
                /// <summary> Path to Content/Assets/Textures/dummySprite.png </summary>
                public const string dummySprite_png = "Content/Assets/Textures/dummySprite.png";
                
                /// <summary> Path to Content/Assets/Textures/exit_bt.PNG </summary>
                public const string exit_bt_PNG = "Content/Assets/Textures/exit_bt.PNG";
                
                /// <summary> Path to Content/Assets/Textures/exit_bt_pressed.PNG </summary>
                public const string exit_bt_pressed_PNG = "Content/Assets/Textures/exit_bt_pressed.PNG";
                
                /// <summary> Path to Content/Assets/Textures/Fire.spritesheet </summary>
                public const string Fire_spritesheet = "Content/Assets/Textures/Fire.spritesheet";
                
                /// <summary> Path to Content/Assets/Textures/mute_active_bt.PNG </summary>
                public const string mute_active_bt_PNG = "Content/Assets/Textures/mute_active_bt.PNG";
                
                /// <summary> Path to Content/Assets/Textures/mute_bt.PNG </summary>
                public const string mute_bt_PNG = "Content/Assets/Textures/mute_bt.PNG";
                
                /// <summary> Path to Content/Assets/Textures/net.png </summary>
                public const string net_png = "Content/Assets/Textures/net.png";
                
                /// <summary> Path to Content/Assets/Textures/pause_bt.PNG </summary>
                public const string pause_bt_PNG = "Content/Assets/Textures/pause_bt.PNG";
                
                /// <summary> Path to Content/Assets/Textures/pause_bt_pressed.PNG </summary>
                public const string pause_bt_pressed_PNG = "Content/Assets/Textures/pause_bt_pressed.PNG";
                
                /// <summary> Path to Content/Assets/Textures/pause_text.PNG </summary>
                public const string pause_text_PNG = "Content/Assets/Textures/pause_text.PNG";
                
                /// <summary> Path to Content/Assets/Textures/ready.png </summary>
                public const string ready_png = "Content/Assets/Textures/ready.png";
                
                /// <summary> Path to Content/Assets/Textures/restart_bt.PNG </summary>
                public const string restart_bt_PNG = "Content/Assets/Textures/restart_bt.PNG";
                
                /// <summary> Path to Content/Assets/Textures/restart_bt_pressed.PNG </summary>
                public const string restart_bt_pressed_PNG = "Content/Assets/Textures/restart_bt_pressed.PNG";
                
                /// <summary> Path to Content/Assets/Textures/resume_bt.PNG </summary>
                public const string resume_bt_PNG = "Content/Assets/Textures/resume_bt.PNG";
                
                /// <summary> Path to Content/Assets/Textures/resume_bt_pressed.PNG </summary>
                public const string resume_bt_pressed_PNG = "Content/Assets/Textures/resume_bt_pressed.PNG";
                
                /// <summary> Path to Content/Assets/Textures/rope_3x1.png </summary>
                public const string rope_3x1_png = "Content/Assets/Textures/rope_3x1.png";
                
                /// <summary> Path to Content/Assets/Textures/scoreboard.PNG </summary>
                public const string scoreboard_PNG = "Content/Assets/Textures/scoreboard.PNG";
                
                /// <summary> Path to Content/Assets/Textures/scoreboard_timein.PNG </summary>
                public const string scoreboard_timein_PNG = "Content/Assets/Textures/scoreboard_timein.PNG";
                
                /// <summary> Path to Content/Assets/Textures/scoreboard_timeout.PNG </summary>
                public const string scoreboard_timeout_PNG = "Content/Assets/Textures/scoreboard_timeout.PNG";
                
                /// <summary> Path to Content/Assets/Textures/static_ball_shines.PNG </summary>
                public const string static_ball_shines_PNG = "Content/Assets/Textures/static_ball_shines.PNG";
                
                /// <summary> Path to Content/Assets/Textures/taptostart.png </summary>
                public const string taptostart_png = "Content/Assets/Textures/taptostart.png";
                
                /// <summary> Path to Content/Assets/Textures/timeover.PNG </summary>
                public const string timeover_PNG = "Content/Assets/Textures/timeover.PNG";
                
                /// <summary> Texture names from spritesheet Content/Assets/Textures/BallFire.spritesheet </summary>
                public struct BallFire_spritesheet_TextureName
                {
                }
                
                /// <summary> Texture names from spritesheet Content/Assets/Textures/Fire.spritesheet </summary>
                public struct Fire_spritesheet_TextureName
                {
                    
                    public const string Fire_01_ = "Fire (01)";
                    
                    public const string Fire_02_ = "Fire (02)";
                    
                    public const string Fire_03_ = "Fire (03)";
                    
                    public const string Fire_04_ = "Fire (04)";
                    
                    public const string Fire_05_ = "Fire (05)";
                    
                    public const string Fire_06_ = "Fire (06)";
                    
                    public const string Fire_07_ = "Fire (07)";
                    
                    public const string Fire_08_ = "Fire (08)";
                    
                    public const string Fire_09_ = "Fire (09)";
                    
                    public const string Fire_10_ = "Fire (10)";
                    
                    public const string Fire_11_ = "Fire (11)";
                }
            }
            
            public sealed class Materials
            {
                
                /// <summary> Path to Content/Assets/Materials/NetMaterial.wmat </summary>
                public const string NetMaterial = "Content/Assets/Materials/NetMaterial.wmat";
                
                /// <summary> Path to Content/Assets/Materials/RopeMaterial.wmat </summary>
                public const string RopeMaterial = "Content/Assets/Materials/RopeMaterial.wmat";
            }
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/GamePlayScene.wscene </summary>
            public const string GamePlayScene = "Content/Scenes/GamePlayScene.wscene";
        }
    }
}
